import type { Itinerary } from './types'

// Full itineraries: Dubai, Maldives, Singapore, Bangkok, Bali, Istanbul.
export const asia: Record<string, Itinerary> = {
  // Dubai
  'Dubai Global Village Entry Ticket': [
    ['Arrival at Global Village', 'Your clients arrive at Global Village on Sheikh Mohammed Bin Zayed Road and enter through the main gate with their entrance ticket. The park opens in the late afternoon and is at its liveliest once the sun goes down, when the pavilions, fountains and walkways light up. Maps are available at the entrance, and there is plenty of seating, prayer rooms and family facilities throughout the park.'],
    ['Country pavilions', 'The heart of Global Village is its collection of country pavilions, each styled on the architecture of the nation it represents. Inside, stalls sell crafts, textiles, spices, perfumes and souvenirs from dozens of countries across Asia, Africa, Europe and the Americas. It is an easy place to spend an hour or more browsing, bargaining and picking up gifts, all within a short walk of each other.'],
    ['Landmark replicas and the lake', 'Scaled-down replicas of world landmarks sit around the park and make popular photo stops, especially after dark when they are lit up. A central lake runs through the grounds, with water features, bridges and seating along its edge. It is a relaxed stretch between the busier pavilions, and a good spot to pause with a drink and watch the crowds pass.'],
    ['Street food and dining', 'Global Village is known for its food, with hundreds of kiosks and restaurants serving dishes from around the world. Your clients can try anything from Turkish ice cream and Indian chaat to Korean street snacks, Emirati sweets and grilled meats. Food and drinks are paid for separately at each stall, so it is worth arriving hungry and sharing plates to taste as much as possible.'],
    ['Shows, rides and fireworks', 'The main stage and smaller performance areas host cultural dance, music and stunt shows through the evening, and the Carnaval area offers rides for children and thrill-seekers at an extra cost. On selected nights, usually weekends and holidays, fireworks light up the sky over the park. Check the season’s schedule when booking so your clients can plan their visit around the shows they most want to see.'],
  ],
  'Premium Desert Safari': [
    ['Hotel pickup', 'A driver collects your clients from their Dubai hotel in the afternoon in a 4x4 vehicle, usually shared with a small group unless a private safari is booked. The drive out of the city takes around 45 minutes to an hour, heading towards the red dunes of the desert conservation areas. Along the way the skyline gives way to open desert, and the driver will explain the plan for the evening.'],
    ['Dune bashing', 'At the edge of the desert the tyres are deflated and the adventure begins. Experienced drivers take the 4x4 up, over and along the dunes for around 30 to 40 minutes of thrilling, roller-coaster driving. It is exciting but controlled, and the driver adjusts the pace to the group. Clients who prefer a gentler ride should mention it at pickup, and the drive is not recommended for pregnant travellers or anyone with back problems.'],
    ['Sunset on the dunes', 'The vehicles stop on a high dune as the sun sets over the desert, turning the sand deep orange and red. This is the classic photo moment of the safari, with plenty of time to walk along the ridges, take pictures and enjoy the quiet. Sandboarding is usually offered here too, letting your clients slide down the slopes on a board before the drive continues to camp.'],
    ['Traditional desert camp', 'The evening continues at a Bedouin-style camp with low seating, carpets and lantern light. Your clients can take a short camel ride, have henna painted on their hands, try on traditional dress and taste Arabic coffee and dates. Quad biking is available at most camps for an extra charge. The camp has restrooms, and the atmosphere is relaxed and family-friendly.'],
    ['Barbecue dinner and live shows', 'Dinner is a buffet with grilled meats, salads, rice and vegetarian dishes, served with soft drinks, water, tea and coffee. As your clients eat, live entertainment takes place on the central stage, typically including a tanoura dancer, a fire show and a belly dance performance. After dinner, the 4x4 takes the group back to their hotels, arriving in the city late in the evening.'],
  ],
  'Burj Khalifa At The Top': [
    ['Check-in at The Dubai Mall', 'Your clients head to the At The Top entrance on the lower ground level of The Dubai Mall, a short walk from the Dubai Metro link bridge. They should arrive around 15 minutes before their time slot, with their tickets on their phone or printed. After a security check they join the entry line for their slot, which moves much faster than buying tickets on the day.'],
    ['Exhibition walkway', 'A moving walkway leads through an exhibition that tells the story of the tower, from the idea and design to the engineering and construction challenges of building the world’s tallest structure. Photographs, models and multimedia displays explain how the tower was built to withstand desert winds and heat. It sets the scene nicely before the ride to the top.'],
    ['High-speed lift', 'One of the fastest lifts in the world carries your clients up to level 124 in around a minute, with a light and sound show on the walls as they rise. Their ears may pop on the way up. The doors open onto the observation deck around 450 metres above the ground, with floor-to-ceiling windows and immediate views across the city.'],
    ['Observation decks, levels 124 and 125', 'From the indoor deck and the open-air terrace on level 124, your clients look down on the Dubai Fountain, the old town and the coast, with the desert stretching away inland. Level 125 adds more space and viewing points. Digital telescopes help pick out landmarks, and the views work equally well by day, at sunset and after dark. Sunset slots sell out first.'],
    ['Return to The Dubai Mall', 'When they are ready, your clients take the lift back down and exit into The Dubai Mall, where the souvenir shop, restaurants and cafés are close by. The evening Dubai Fountain shows take place on the lake just outside every half hour, and the fountain boardwalk is a short walk away. There is no fixed time limit on the decks, so clients can take their time.'],
  ],
  'Marina Dhow Cruise': [
    ['Meeting point at Dubai Marina', 'Your clients meet the crew at the Dubai Marina jetty in the evening, about half an hour before departure. The marina promenade is lined with restaurants and cafés, so it is easy to arrive early and take a stroll first. The crew checks in the guests and welcomes them aboard a traditional wooden dhow that has been fitted out for dining, with an upper open deck and an air-conditioned lower deck.'],
    ['Welcome on board', 'Once everyone is aboard, guests are shown to their tables and offered welcome drinks, with soft drinks, water, tea and coffee included throughout. The boat sets off slowly along the man-made channel of the marina. The open upper deck is the best place for photos as the lights come on, while the lower deck offers a cooler, quieter setting.'],
    ['Cruising the marina skyline', 'The dhow cruises past the towers of Dubai Marina and Jumeirah Beach Residence, one of the densest clusters of skyscrapers in the world. As night falls, the buildings light up and reflect on the water, giving your clients a very different view of the city from street level. The captain keeps a gentle pace, so the ride is smooth and comfortable.'],
    ['International buffet dinner', 'Dinner is an international buffet with Arabic, Indian and continental dishes, including salads, grilled items, rice, curries and desserts, with vegetarian options. Guests eat at their own tables with background music, and on many cruises there is light entertainment such as a tanoura dance performance. Alcoholic drinks are not included and are only available on licensed boats.'],
    ['Return to the jetty', 'After around two hours on the water, the dhow returns to the jetty. Your clients can walk back along the marina promenade, stop for dessert or coffee, or continue to The Walk at JBR nearby. Hotel transfers are not included as standard, but our team can add a private or shared transfer so the evening runs smoothly from start to finish.'],
  ],
  'Old Dubai Walking Tour': [
    ['Al Fahidi Historical Neighbourhood', 'The tour begins in Al Fahidi, one of the oldest parts of the city, with narrow lanes and restored houses built from coral stone and gypsum. The guide explains how the wind towers on the rooftops caught the breeze to cool the homes long before air conditioning. Small galleries, cafés and cultural centres now fill many of the old houses, making it a peaceful place to start.'],
    ['Arabic coffee and dates', 'Your clients stop for Arabic coffee and dates, the traditional welcome in Emirati homes. The guide shares the customs around serving coffee, such as how many cups to accept and how to signal that you have had enough. It is a relaxed break and a chance to ask questions about daily life, culture and how the city has changed over the past decades.'],
    ['Abra ride across Dubai Creek', 'The group walks down to the creek and boards an abra, the small wooden water taxi that has carried people between Bur Dubai and Deira for generations. The short crossing gives great views of the busy waterfront, the dhows unloading cargo and the mix of old buildings and modern towers. It is one of the most memorable and authentic moments of a visit to Dubai.'],
    ['Deira Spice Souk', 'On the Deira side, the guide leads the group through the spice souk, where sacks of saffron, cardamom, dried lemons, frankincense and colourful spices line the narrow lanes. Traders are happy to explain what each spice is used for, and your clients can shop if they wish. Bargaining is normal here, and the guide can share tips on fair prices.'],
    ['Gold Souk', 'The walk ends in the famous Gold Souk, where more than 300 shops display gold, diamond and silver jewellery in glittering windows. Prices are based on the daily gold rate plus a charge for the craftsmanship. Your clients can browse at their own pace or continue shopping after the tour, and the guide can point out nearby metro stations and taxi ranks for the journey back.'],
  ],

  // Maldives
  'Private Sandbank Picnic': [
    ['Departure from the resort jetty', 'Your clients meet the boat crew at the resort jetty at the agreed time, usually mid-morning to make the most of the light and calmer water. The crew loads the picnic, snorkelling gear, shade and towels, and helps everyone aboard. The boat ride to the sandbank typically takes between 15 and 45 minutes depending on the resort, with clear turquoise water and reef views along the way.'],
    ['Arrival at the private sandbank', 'The boat drops anchor beside a small strip of white sand in the middle of the lagoon, with nothing around it but sea and sky. The crew sets up a shade umbrella, towels and seating, then leaves your clients to enjoy it on their own. It is one of the most photographed experiences in the Maldives, and ideal for honeymooners, proposals and special occasions.'],
    ['Snorkelling and swimming', 'The shallow water around the sandbank is warm and clear, perfect for a swim. With the snorkelling equipment provided, your clients can explore the nearby reef edges, where they may see reef fish, rays and sometimes turtles. The crew advises on safe areas and currents before they go in. Reef-safe sunscreen and a rash vest are recommended because there is little natural shade.'],
    ['Picnic lunch', 'The crew serves a picnic lunch prepared by the resort, usually with sandwiches or wraps, salads, fresh fruit and soft drinks, although menus vary by resort and can often be upgraded. Your clients eat under the umbrella with their feet in the sand. Special requests such as a cake, flowers or sparkling wine can be arranged in advance for celebrations at an extra cost.'],
    ['Return to the resort', 'After around three hours, the boat collects your clients and brings them back to the resort jetty. Timings are flexible within the booking, and the crew keeps an eye on the weather and tide throughout. Most resorts run this experience privately, so the exact inclusions and price depend on the resort your clients are staying at, and our team confirms these with the quote.'],
  ],
  'Manta Ray Snorkelling': [
    ['Departure and briefing', 'Your clients meet the marine guide at the resort jetty or dive centre for a short briefing about manta rays, how to behave in the water and the protection rules at Hanifaru Bay. They are fitted with snorkelling gear, and the guide checks swimming confidence. The trip usually runs in the morning or early afternoon, depending on the tides and where the mantas are feeding that day.'],
    ['Speedboat to Hanifaru Bay', 'A speedboat takes the group across Baa Atoll to Hanifaru Bay, a UNESCO Biosphere Reserve. During the south-west monsoon, roughly from June to November, currents push plankton into the bay and manta rays gather to feed, sometimes in large numbers. Access is strictly managed by rangers, and only a limited number of boats and snorkellers are allowed in at one time.'],
    ['Snorkelling with manta rays', 'Once the rangers give the go-ahead, the group slips quietly into the water with their guide. Manta rays, which can have a wingspan of three metres or more, glide and loop through the plankton, often passing very close. Swimmers must keep their distance, avoid touching the animals and float calmly at the surface. Sightings depend on nature and cannot be guaranteed, but the season offers the best chances.'],
    ['Reef snorkel', 'If time and conditions allow, the boat stops at a nearby reef for a second snorkel. Here your clients may see colourful reef fish, turtles and reef sharks in clear, shallow water. It is a good chance to enjoy the underwater world at a more relaxed pace after the excitement of the mantas. The guide stays close and points out marine life along the way.'],
    ['Return to the resort', 'The speedboat returns to the resort, with water and towels on board. The whole trip takes around half a day. Underwater photos can often be bought from the dive centre afterwards. Outside the manta season, Hanifaru Bay is closed to snorkellers, so our team will suggest alternative manta or reef trips depending on your clients’ travel dates and resort.'],
  ],
  'Sunset Dolphin Cruise': [
    ['Late afternoon departure', 'Your clients board the boat at the resort jetty in the late afternoon, about two hours before sunset. The crew welcomes everyone aboard and serves soft drinks as the boat sets off. Most resorts use a traditional Maldivian dhoni or a comfortable speedboat with shaded seating, and the cruise is suitable for all ages, including young children with adult supervision.'],
    ['Searching for dolphins', 'The boat heads to channels and open water around the atoll where spinner dolphins are often seen. Spinners are known for leaping and spinning out of the water, and pods can number dozens or even hundreds. The captain slows down when dolphins are spotted, and they often come close to ride the bow wave. Sightings are common but, as with all wildlife, not guaranteed.'],
    ['Golden hour on the water', 'As the sun lowers, the light turns warm and golden over the lagoon and neighbouring islands. It is the best time for photos of the dolphins, the boat and the sea. The crew serves snacks and more soft drinks while the boat drifts or cruises slowly. Alcoholic drinks can usually be added at an extra cost depending on the resort.'],
    ['Sunset over the Indian Ocean', 'The boat stops in open water to watch the sun set over the horizon, one of the simplest and most memorable moments of a Maldives holiday. With little light pollution, the sky often turns orange, pink and purple. For couples, the crew can arrange sparkling wine or a small celebration on request, which our team can add to the booking.'],
    ['Return to the resort', 'The boat returns to the resort jetty around dusk, in time for dinner. The cruise lasts about two hours in total. Timings shift slightly through the year with the sunset. Because it runs on most atolls, this is an easy add-on for any Maldives package, and many resorts offer both shared and private departures.'],
  ],
  'Malé City Tour': [
    ['Arrival in Malé', 'Your clients arrive in Malé by boat from their resort or from the airport island, where they meet their local guide near the jetty. Malé is one of the most densely built capitals in the world, a compact island packed with colourful buildings, mosques, markets and busy streets. It is easy to explore on foot, and the guide keeps the pace comfortable.'],
    ['Malé Friday Mosque', 'The first stop is the Hukuru Miskiy, or Old Friday Mosque, built in the 17th century from carved coral stone. Its walls are decorated with intricate carvings and Arabic calligraphy, and the lacquered woodwork inside is some of the finest in the country. Visitors dress modestly and may need permission to enter, so the guide explains the rules before the visit.'],
    ['Local fish market', 'The guide leads the group to the fish market near the harbour, the busiest place in the city in the late afternoon when the fishing boats return. Tuna, the country’s main catch, is carried in and cut by hand on tiled floors. It gives your clients an authentic glimpse into Maldivian daily life, far from the resort islands.'],
    ['Fruit and vegetable market', 'Next door, the local market sells fruit, vegetables, spices, betel leaves, dried fish and homemade snacks from islands across the country. Your clients can taste local treats such as coconut-based sweets, and the guide explains how these foods feature in Maldivian cooking. It is also a good place to pick up small souvenirs.'],
    ['Republic Square and the harbour', 'The tour ends at Republic Square by the harbour, where the huge Maldivian flag flies and ferries come and go. From here, the guide points out nearby sights such as the Islamic Centre and the Sultan Park. Your clients can then return to the jetty for their boat, or stay on to explore cafés and shops. Transfers to Malé are arranged separately.'],
  ],

  // Singapore
  'Gardens by the Bay': [
    ['Arrival at Gardens by the Bay', 'Your clients arrive at Gardens by the Bay, a short walk from Bayfront MRT station and Marina Bay Sands. The outdoor gardens are free to explore, while the two cooled conservatories need a ticket. It is best to start with the conservatories during the day, when the Singapore heat makes their cool air especially welcome, and save the Supertrees for the evening.'],
    ['Flower Dome', 'The Flower Dome is the largest glass greenhouse in the world, kept mild and dry like a Mediterranean spring. Inside, gardens represent regions from South Africa and Australia to the Mediterranean and California, with ancient olive trees, baobabs and succulents. The central flower field changes with regular seasonal displays, so there is always something new to see even for repeat visitors.'],
    ['Cloud Forest', 'The Cloud Forest recreates the cool, misty world of tropical mountains. Your clients are greeted by a 35-metre indoor waterfall tumbling down a mountain covered in orchids, ferns and pitcher plants. A lift takes them to the top, and walkways spiral down around the mountain, with displays about biodiversity and climate along the way. It is one of the most striking indoor spaces in Asia.'],
    ['Supertree Grove', 'Outside, the Supertree Grove is a cluster of tree-like vertical gardens up to 50 metres tall, covered with thousands of plants. Your clients can walk freely among them, and the optional OCBC Skyway, a walkway suspended between the Supertrees, gives views over the gardens and the bay for an extra fee. The grove is busiest at dusk, when the Supertrees light up.'],
    ['Garden Rhapsody light show', 'Each evening, the free Garden Rhapsody show brings the Supertrees to life with lights and music. Your clients can lie back on the ground beneath the trees to watch the show, which lasts around 15 minutes. Afterwards, the Marina Bay waterfront, the Spectra light show at Marina Bay Sands and plenty of dining options are within walking distance.'],
  ],
  'Universal Studios Singapore': [
    ['Arrival on Sentosa', 'Your clients travel to Resorts World Sentosa by taxi, the Sentosa Express monorail from VivoCity, or on foot across the Sentosa Boardwalk. They enter Universal Studios Singapore with their one-day ticket, passing the famous rotating Universal globe at the entrance. Arriving at opening time is the best way to enjoy the most popular rides before the queues build up.'],
    ['Hollywood and New York', 'The first two zones recreate classic film streets, with Hollywood’s Walk of Fame and theatres and the brownstone streets of New York. Characters often appear for photos here, and shows and parades take place through the day. The Lights, Camera, Action attraction, with its special effects storm, is a highlight for those who enjoy behind-the-scenes filmmaking.'],
    ['Sci-Fi City', 'Sci-Fi City is home to the park’s biggest thrills, including the Battlestar Galactica duelling roller coasters and the Transformers ride, a 3D dark ride that puts guests in the middle of the battle between Autobots and Decepticons. These rides have height restrictions and can have long queues, so an Express pass, available at extra cost, is worth considering on busy days.'],
    ['Ancient Egypt and The Lost World', 'In Ancient Egypt, Revenge of the Mummy is an indoor roller coaster in the dark. The Lost World combines Jurassic Park, with its water ride through dinosaur territory, and Waterworld, a live stunt show with explosions and jet skis. Your clients should check the show times on arrival, and those on the river ride should be ready to get wet.'],
    ['Far Far Away and Madagascar', 'The final zones are ideal for younger children. Far Far Away is dominated by Shrek’s castle, with gentle rides and a 4D film, while Madagascar offers a boat ride and a carousel with characters from the films. Restaurants and snack stands are spread across the park, and the day usually ends with shopping for souvenirs before heading back across Sentosa.'],
  ],
  'Night Safari': [
    ['Arrival at Mandai Wildlife Reserve', 'Your clients arrive at the Mandai Wildlife Reserve in the north of Singapore around dusk, when the Night Safari opens. The entrance village has restaurants, shops and a stage where a short cultural performance often takes place. It is worth having dinner here before the safari begins, as the park is at its most active after dark.'],
    ['Creatures of the Night show', 'The Creatures of the Night show introduces nocturnal animals such as owls, otters and civets and explains how they are adapted to life in the dark. It is informative and entertaining, especially for children, and lasts around 20 minutes. Seating is first come, first served, so your clients should arrive a little early to get a good view.'],
    ['Tram safari', 'The tram ride takes around 40 minutes and travels through habitats representing the Himalayan foothills, the Indian subcontinent, Africa and Southeast Asia. With live commentary, your clients see animals such as Asian elephants, rhinos, hippos, striped hyenas and Malayan tapirs in naturalistic enclosures under soft lighting. Flash photography is not allowed, to protect the animals.'],
    ['Walking trails', 'After the tram, your clients can explore four walking trails at their own pace. The Leopard Trail, Fishing Cat Trail, East Lodge Trail and Wallaby Trail bring them closer to smaller animals, including clouded leopards, flying squirrels, slow lorises and wallabies. The trails are well marked and lit, and take between 20 minutes and an hour depending on how much they explore.'],
    ['Return to the entrance', 'The trails loop back to the entrance village, where your clients can pick up souvenirs or a late snack before heading back to the city. Taxis and shuttle buses serve the park, and hotel transfers can be added to the booking. The whole visit takes around four hours, making it an ideal evening activity after a day of sightseeing.'],
  ],
  'Singapore River Cruise': [
    ['Boarding at Clarke Quay', 'Your clients board a traditional wooden bumboat at the Clarke Quay jetty, in the lively riverside area of restaurants and bars. Boats depart regularly through the day and evening, and the journey is suitable for all ages. Evening departures are the most popular because the city lights make the skyline look its best, but daytime trips are quieter and cooler.'],
    ['Historic quays', 'The boat glides along the Singapore River past Clarke Quay and Boat Quay, where old warehouses and shophouses once served the trading boats that built the city’s fortune. Today they are home to restaurants and bars. The recorded commentary explains the river’s role in Singapore’s history as a port and how the waterfront was cleaned up and restored.'],
    ['Civic District', 'Next, the cruise passes the Civic District, with colonial landmarks such as the Asian Civilisations Museum, the Old Parliament House and the Fullerton Hotel, once the General Post Office. The boat also passes under several historic bridges, including Cavenagh Bridge, one of the oldest in the city. It is a pleasant way to see these sights without the heat of walking.'],
    ['Merlion and Marina Bay', 'The boat heads into Marina Bay and passes the Merlion, the city’s half-lion, half-fish symbol, spouting water into the bay. Your clients get open views of Marina Bay Sands, the ArtScience Museum and the Esplanade theatres. In the evening, the Spectra light and water show can sometimes be seen from the water, depending on the timing.'],
    ['Return or stop-off', 'After around 40 minutes to an hour, the boat returns to Clarke Quay, or your clients can get off at another jetty along the route, depending on the ticket. It is an easy add-on to any Singapore itinerary, and combines well with dinner at Clarke Quay or an evening at Gardens by the Bay across the water.'],
  ],

  // Bangkok
  'Grand Palace & Temples Tour': [
    ['Hotel pickup', 'Your clients are collected from their Bangkok hotel in the morning by their guide, who explains the plan for the day and the dress code: shoulders and knees must be covered at the temples, and shoes must be removed inside the halls. The group then heads to the Rattanakosin area, the historic heart of the city, starting early to avoid the midday heat and the largest crowds.'],
    ['Grand Palace', 'The Grand Palace was the official residence of the kings of Siam from 1782 and is still used for royal ceremonies. Your clients walk through courtyards of glittering buildings decorated with gold leaf, mosaics and mythical guardian statues. The guide explains the mix of Thai, Khmer and European architecture and the history of the Chakri dynasty. Some halls are closed to visitors on royal occasions.'],
    ['Temple of the Emerald Buddha', 'Within the palace grounds stands Wat Phra Kaew, Thailand’s most sacred temple. It houses the Emerald Buddha, a small statue carved from jade, dressed in seasonal robes changed by the King three times a year. The murals around the cloister tell the story of the Ramakien, the Thai version of the Ramayana. Photography is not allowed inside the main hall.'],
    ['Wat Pho', 'A short walk away, Wat Pho is home to the famous Reclining Buddha, 46 metres long and covered in gold leaf, with mother-of-pearl inlays on its feet. The temple complex is one of the oldest in Bangkok and is known as the birthplace of traditional Thai massage, which is still taught here. Your clients can drop coins into the bronze bowls for good luck.'],
    ['Wat Arun and return', 'The group crosses the Chao Phraya River by ferry to Wat Arun, the Temple of Dawn, with its tall central spire decorated with pieces of coloured porcelain. The views of the river from its terraces are among the best in the city. After the visit, the guide brings your clients back to their hotel, around four hours after pickup, with time for lunch in the afternoon.'],
  ],
  'Floating Market Day Trip': [
    ['Early pickup in Bangkok', 'Your clients are collected from their hotel early in the morning, usually around 7am, because the floating market is at its busiest and most authentic in the morning. The drive to Damnoen Saduak in Ratchaburi province takes around one and a half to two hours. The guide uses the journey to explain the history of canal life in central Thailand and what to expect at the markets.'],
    ['Maeklong Railway Market', 'On selected tours, the first stop is the Maeklong Railway Market, where traders set up stalls right on the railway track. Several times a day, the train slowly passes through, and the vendors quickly pull back their awnings and goods, then set them up again as soon as it has gone. It is one of the most unusual sights in Thailand, and timing depends on the train schedule.'],
    ['Longtail boat ride', 'At Damnoen Saduak, your clients board a boat to explore the network of narrow canals. They pass houses on stilts, gardens and orchards, and see how people have lived and traded along the water for generations. The boat ride is included in the tour and gives a relaxed view of the area before arriving at the busiest part of the market.'],
    ['Damnoen Saduak Floating Market', 'At the heart of the market, vendors paddle small wooden boats piled with tropical fruit, noodles, coconut pancakes and souvenirs. Your clients can buy snacks directly from the boats, try fresh mango sticky rice or coconut ice cream, and browse the stalls along the canal banks. Bargaining is normal for souvenirs, and the guide can help with fair prices.'],
    ['Return to Bangkok', 'After some free time at the market, the group returns to Bangkok, arriving back at the hotel in the early afternoon. Some tours include a stop at a coconut sugar farm on the way back, where your clients can see how palm sugar is made. The day is relaxed, with plenty of photo opportunities, and suits families and first-time visitors.'],
  ],
  'Chao Phraya Dinner Cruise': [
    ['Check-in at the river pier', 'Your clients arrive at the departure pier in the early evening, usually at a riverside shopping area such as ICONSIAM or River City, around 30 minutes before boarding. After checking in, they board the cruise boat and are shown to their table. Most boats have an air-conditioned lower deck and an open upper deck for the best views.'],
    ['Welcome and departure', 'Guests are welcomed aboard with a drink, and the boat sets off along the Chao Phraya, known as the River of Kings. As the sun sets, the lights of the riverside hotels, temples and bridges begin to shine. The river is busy with ferries and long-tail boats, and the cruise gives a real sense of how central the river is to life in Bangkok.'],
    ['International and Thai buffet', 'Dinner is a buffet of Thai and international dishes, often including seafood, curries, stir-fries, salads and desserts, with vegetarian options. While guests dine, live music and a singer entertain on board, and some cruises include a short Thai dance performance. Drinks other than the welcome drink are usually paid for separately.'],
    ['Wat Arun and the Grand Palace', 'The highlight of the cruise is passing Wat Arun, the Temple of Dawn, lit up in gold against the night sky, and the illuminated rooftops of the Grand Palace on the opposite bank. The boat slows down here so your clients can take photos from the open deck. These are some of the most beautiful views of Bangkok by night.'],
    ['Return to the pier', 'After around two hours, the boat returns to the pier. From there, your clients can explore the shopping mall or take a taxi or the free shuttle boat to the Saphan Taksin BTS station. Hotel transfers can be added to the booking. The cruise is especially popular for honeymooners, birthdays and families.'],
  ],
  'Tuk-Tuk Street Food Tour': [
    ['Meeting the guide', 'Your clients meet their guide in the early evening at a central meeting point, usually near a BTS or MRT station. After a quick introduction and a check on any food allergies or dietary needs, the group climbs into tuk-tuks, the three-wheeled taxis that are a symbol of Bangkok. The ride through the city’s traffic and lights is an adventure in itself.'],
    ['Yaowarat (Chinatown)', 'The first stop is Yaowarat, Bangkok’s Chinatown, which comes alive after dark with neon signs and hundreds of street food stalls. Your clients taste local favourites such as crispy pork, rice noodle rolls, grilled seafood and dumplings. The guide explains the history of the Chinese community in Bangkok and chooses stalls known to locals for their quality.'],
    ['Local noodle and dessert stops', 'The tour continues to smaller, family-run eateries that many visitors would never find on their own, often including a famous pad thai or boat noodle shop. For dessert, your clients might try mango sticky rice, Thai-style roti or coconut ice cream. Soft drinks are included, and portions are designed so everyone can try a little of everything.'],
    ['Pak Khlong Talat flower market', 'Next, the tuk-tuks stop at Pak Khlong Talat, the city’s main flower market, which is open around the clock and busiest at night. Mountains of marigolds, orchids, roses and lotus flowers are sorted and sold for temples, offerings and ceremonies. The colours and scents are impressive, and it is a great photo stop away from the food.'],
    ['Temples by night and finish', 'Many tours include a drive past illuminated temples such as Wat Pho or the Grand Palace, or a stop at a viewpoint. The tour ends back in the city centre after around four hours, with your clients well fed. It is a great evening activity for foodies, and the guide can recommend bars or rooftops to continue the night.'],
  ],

  // Bali
  'Mount Batur Sunrise Trek': [
    ['Early morning pickup', 'Your clients are collected from their hotel very early, usually between 2am and 3am depending on their location, for the drive to Kintamani in central Bali. Some tours stop briefly for a light snack or coffee. The early start is necessary to reach the summit before sunrise. Warm layers, good walking shoes and a small backpack are recommended because it can be cold at the top.'],
    ['Trailhead and briefing', 'At the base of the volcano, the group meets a certified local trekking guide, who gives a short safety briefing and hands out torches. The trek begins in the dark at around 4am, following a path through farmland and forest before the trail becomes steeper, with loose volcanic gravel near the top. The guide sets a steady pace and waits for everyone.'],
    ['The climb', 'The climb takes around two hours and is moderately challenging, suitable for people with reasonable fitness. The path is steep in places, and your clients will see a line of torches from other groups winding up the mountain. Along the way, there are rest stops where the guide shares information about the volcano, which last erupted in 2000, and the local villages around the lake.'],
    ['Sunrise at the summit', 'At the summit, 1,717 metres above sea level, your clients watch the sun rise over Lake Batur, with Mount Agung and, on clear days, Mount Rinjani on Lombok in the distance. The guide prepares breakfast, often eggs or bananas steamed in volcanic vents, with bread and hot drinks. Long-tailed monkeys often appear, hoping for a share of the food.'],
    ['Crater walk and descent', 'After breakfast, the guide may lead the group around part of the crater rim, where steam rises from the ground. The descent takes around one and a half hours and offers views of the black lava fields from past eruptions. After returning to the base, some tours stop at a natural hot spring or coffee plantation before driving back to the hotel by late morning.'],
  ],
  'Ubud Rice Terraces & Temples': [
    ['Hotel pickup with a private driver', 'Your clients are collected from their hotel in the morning by a private driver, who stays with them throughout the day. The driver adapts the pace and order of the stops to their interests, and can recommend places for lunch. Temples require a sarong, which is usually provided at the entrance, and shoulders should be covered.'],
    ['Tegallalang Rice Terraces', 'The first stop is the Tegallalang Rice Terraces, north of Ubud, where green paddies step down the sides of a deep valley. The terraces are irrigated using the traditional Balinese subak system, which is recognised by UNESCO. Your clients can walk down among the terraces on narrow paths, and there are swings and cafés with views for those who want to relax.'],
    ['Tirta Empul Temple', 'Tirta Empul is a Hindu water temple built around a sacred spring. Balinese people come here to bathe in the purification pools, moving along rows of spouts in a ritual of cleansing. Your clients can watch or take part with a guide’s help, wearing the appropriate sarong. The temple’s courtyards, shrines and carp ponds are peaceful and beautiful.'],
    ['Sacred Monkey Forest Sanctuary', 'Back in Ubud, the Sacred Monkey Forest is a jungle sanctuary with ancient temples, moss-covered statues and huge banyan trees. It is home to hundreds of long-tailed macaques. They are used to visitors but can be cheeky, so your clients should keep sunglasses, bags and food secure and follow the staff’s advice. The walkways are shaded and cool.'],
    ['Ubud town', 'The day ends in Ubud town, with time to visit the Ubud Art Market, the Royal Palace and the many galleries, boutiques and cafés. It is the cultural heart of Bali, known for its painting, dance, woodcarving and silverwork. The driver then brings your clients back to their hotel in the late afternoon, after around six hours in total.'],
  ],
  'Uluwatu Kecak Fire Dance': [
    ['Afternoon pickup', 'Your clients are collected from their hotel in the mid to late afternoon and driven to the Bukit Peninsula in the south of Bali. The drive time depends on traffic and the hotel’s location. The aim is to arrive with enough time to explore the temple before the show, which starts shortly before sunset. A sarong and sash are provided at the temple entrance.'],
    ['Uluwatu Temple', 'Pura Luhur Uluwatu is one of Bali’s six key sea temples, perched on a cliff about 70 metres above the Indian Ocean. Your clients can walk along the clifftop paths for dramatic views of the waves crashing below. The temple is home to monkeys that are known to snatch glasses, hats and phones, so visitors should keep their belongings safe.'],
    ['Sunset from the clifftop', 'As the sun lowers, the sky over the ocean turns orange and pink. The clifftop viewpoints are among the best places in Bali to watch the sunset, and your clients can take photos before heading to the amphitheatre. Seats are unreserved, so arriving early helps to secure a good view of both the stage and the sea.'],
    ['Kecak and fire dance', 'The Kecak dance is performed in an open-air amphitheatre on the cliff. Dozens of men sit in circles and chant rhythmically, creating the music with their voices, while dancers act out an episode from the Ramayana. The show ends with a dramatic fire dance, where a performer kicks burning coconut husks across the stage. The performance lasts about an hour.'],
    ['Return to the hotel', 'After the show, your clients return to their hotel, or can stop for a seafood dinner at Jimbaran Bay on the way, which is a popular option. The whole experience takes around three to four hours, depending on the pickup location. It is a highlight for couples, families and anyone interested in Balinese culture.'],
  ],
  'Nusa Penida Day Trip': [
    ['Pickup and fast boat', 'Your clients are collected from their hotel early in the morning and taken to Sanur harbour, where they board a fast boat to Nusa Penida. The crossing takes around 30 to 45 minutes, depending on the sea. On arrival, they meet their driver and guide, who will take them around the island’s western coast. The island’s roads are narrow and bumpy, so the drive can be slow.'],
    ['Kelingking Beach', 'Kelingking Beach is Nusa Penida’s most famous view, with a cliff shaped like a T-Rex jutting out into the turquoise sea. Your clients can take photos from the viewpoint at the top. The path down to the beach is very steep and only suitable for fit, well-prepared visitors, so most people enjoy the view from above.'],
    ['Broken Beach', 'Broken Beach, or Pasih Uug, is a natural arch in the cliff through which the sea flows into a circular bay. Your clients can walk around the clifftop path for views of the arch and the water below, which often shows striking shades of blue. Manta rays can sometimes be seen from the cliffs here.'],
    ['Angel’s Billabong', 'A short walk from Broken Beach, Angel’s Billabong is a natural rock pool on the edge of the ocean, with clear water when the tide is low. Swimming is not always safe, as waves can suddenly break over the rocks, so your clients should follow the guide’s advice. It is a spectacular spot for photos.'],
    ['Crystal Bay snorkelling and return', 'The last stop is usually Crystal Bay or another sheltered spot for snorkelling, where your clients can see coral and tropical fish, conditions permitting. Lunch is included at a local restaurant during the day. The fast boat returns to Sanur in the afternoon, and your clients are driven back to their hotel in the early evening.'],
  ],

  // Istanbul
  'Bosphorus Cruise': [
    ['Boarding at Eminönü', 'Your clients board the boat at the Eminönü pier, beside the Galata Bridge and the New Mosque. Boats depart regularly through the day, and the audio commentary is available in several languages. It is worth arriving early to find a seat on the open deck, which has the best views, while the enclosed deck is warmer in winter.'],
    ['Dolmabahçe Palace', 'The boat heads north along the European shore and passes Dolmabahçe Palace, the grand 19th-century home of the late Ottoman sultans, with its long white façade facing the water. It was built in a mix of European styles and later became the residence of Atatürk, the founder of modern Turkey. The views from the water show its full length.'],
    ['Ortaköy and the Bosphorus Bridge', 'Next, the boat passes the Ortaköy Mosque, a small baroque mosque on the water’s edge, with the Bosphorus Bridge towering behind it. The bridge, opened in 1973, connects Europe and Asia and is one of the most photographed views in Istanbul. The commentary explains the strait’s importance as a shipping route between the Black Sea and the Mediterranean.'],
    ['Waterfront mansions and Rumeli Fortress', 'The boat continues past the yalıs, elegant wooden mansions built by wealthy Ottoman families on the water’s edge, as well as the Çırağan Palace. Your clients then see Rumeli Fortress, built by Sultan Mehmed II in 1452 to control the strait before the conquest of Constantinople. The boat usually turns around near the Fatih Sultan Mehmet Bridge.'],
    ['Asian shore and return', 'On the way back, the boat follows the Asian shore, passing Beylerbeyi Palace and the charming neighbourhoods of Kuzguncuk and Üsküdar. It returns to Eminönü after around two hours. From the pier, your clients can walk to the Spice Bazaar or cross the Galata Bridge to Karaköy for lunch or dinner.'],
  ],
  'Hagia Sophia & Blue Mosque Tour': [
    ['Meeting in Sultanahmet', 'Your clients meet their guide in Sultanahmet Square, in the heart of the old city, between the Blue Mosque and Hagia Sophia. The guide gives an overview of the history of Byzantium, Constantinople and Istanbul, and explains the dress code for the mosques: women should cover their hair, and shoulders and knees should be covered for everyone.'],
    ['Hippodrome', 'The tour begins at the Hippodrome, once the centre of Byzantine public life, where chariot races were held for crowds of up to 100,000 people. Today it is a long square, but three monuments remain: the Egyptian Obelisk, over 3,500 years old, the bronze Serpent Column and the Walled Obelisk. The guide brings the ancient arena back to life with stories of races and riots.'],
    ['Blue Mosque', 'The Sultan Ahmed Mosque, known as the Blue Mosque, was completed in 1616 and is famous for its six minarets and cascading domes. Inside, more than 20,000 hand-painted Iznik tiles give it its nickname. It is still an active mosque, so it closes to visitors during prayer times, and the guide plans the visit around them. Entry is free.'],
    ['Hagia Sophia', 'Hagia Sophia was built in 537 as the greatest church in the Byzantine Empire, became a mosque after 1453, then a museum, and is again a mosque today. Its vast dome seemed to float above the worshippers. The guide explains its history and points out the mosaics and Islamic calligraphy. Visiting rules and fees for foreign visitors change, so our team confirms the latest arrangements.'],
    ['Basilica Cistern or Topkapı view and finish', 'Depending on the tour, the walk continues to the Basilica Cistern, an underground reservoir with hundreds of columns and two Medusa heads, or ends with views towards Topkapı Palace. The tour finishes in Sultanahmet after around four hours, and the guide can recommend nearby restaurants for lunch, including places serving traditional Turkish meatballs.'],
  ],
  'Grand Bazaar & Spice Market Walk': [
    ['Meeting at the Grand Bazaar', 'Your clients meet their guide at one of the main gates of the Grand Bazaar, near the Beyazıt tram stop. Built in the 15th century, it is one of the oldest and largest covered markets in the world, with more than 60 streets and thousands of shops. The guide explains how the bazaar is organised and shares tips on shopping and bargaining.'],
    ['Inside the Grand Bazaar', 'The walk leads through the bazaar’s vaulted streets, past shops selling carpets, lamps, ceramics, leather goods, jewellery and textiles. The guide shows your clients the oldest section, the Cevahir Bedesten, where valuables were once kept, as well as hidden courtyards called hans where craftsmen still work. It is easy to get lost here, so having a guide is a real advantage.'],
    ['Walk through the old commercial district', 'Leaving the bazaar, the group walks downhill through the busy streets of Mahmutpaşa and Tahtakale, where local people shop for household goods, fabrics and wedding items. It is a lively, authentic side of Istanbul. Along the way, the guide points out historic buildings, mosques and shops that have been run by the same families for generations.'],
    ['Rüstem Pasha Mosque', 'Many walks include a short visit to the Rüstem Pasha Mosque, hidden above shops near the Spice Bazaar. Built by the great architect Mimar Sinan in the 16th century, it is known for having some of the most beautiful Iznik tiles in the city, in shades of blue, red and green. It is quiet and rarely crowded, making it a real hidden gem.'],
    ['Spice Bazaar tastings', 'The walk ends at the Spice Bazaar, also known as the Egyptian Bazaar, near the Eminönü waterfront. Your clients can taste Turkish delight, dried fruit, nuts, herbal teas and spices, and learn which ones to buy. The guide shows them the best stalls, and they can continue shopping on their own afterwards, or take a ferry on the Bosphorus.'],
  ],
  'Traditional Hammam': [
    ['Arrival and changing', 'Your clients arrive at a historic hammam in Sultanahmet, where they are welcomed with a drink and shown to private changing cubicles. They receive a peştemal, a traditional cotton wrap, and slippers. Men and women usually use separate sections, or have separate times, depending on the hammam. Swimwear can be worn underneath if they prefer.'],
    ['Hot room', 'The attendant leads them into the hot room, a marble hall with a large central heated stone called the göbek taşı, under a dome with small star-shaped windows. Your clients lie on the warm marble for around 15 minutes to relax and let the steam open their pores. The atmosphere is calm and quiet, and the architecture is often centuries old.'],
    ['Kese scrub', 'The attendant then gives a traditional kese scrub, using a rough mitt to remove dead skin all over the body. It is vigorous but refreshing and leaves the skin very smooth. Your clients can tell the attendant if they would like a gentler scrub. Warm water is poured over them from copper bowls to rinse.'],
    ['Foam massage', 'Next comes the foam wash, where the attendant fills a cotton cloth with soapy water and creates a cloud of foam that covers your clients from head to toe. They are then washed and gently massaged under the foam, followed by a hair wash. The foam massage is the most famous part of the hammam ritual and very relaxing.'],
    ['Cooling room and tea', 'Finally, your clients are wrapped in fresh towels and taken to the cooling room to rest on sofas with Turkish tea or sherbet. They can take their time before getting dressed. Extra treatments, such as an oil massage or facial, can be added at the hammam. The whole experience takes around two hours, and it is best to book in advance.'],
  ],
}
