import type { Itinerary } from './types'

// Full itineraries: Tokyo, Lisbon, Cape Town, Brașov, Sydney.
export const south: Record<string, Itinerary> = {
  // Tokyo
  'Mount Fuji & Hakone Day Trip': [
    ['Departure from Tokyo', 'Your clients meet their guide at a central Tokyo meeting point early in the morning, usually in Shinjuku or near Tokyo Station, and board a comfortable coach. The drive to Mount Fuji takes around two and a half hours, depending on traffic. On the way, the guide shares stories about the mountain, its role in Japanese culture and art, and what to expect during the day.'],
    ['Mount Fuji Fifth Station', 'Weather and road conditions permitting, the coach climbs to the Fifth Station at around 2,300 metres, where the paved road ends and hiking trails begin in summer. From here, your clients get close-up views of the summit and, on clear days, views over the lakes and forests below. There are shops, a small shrine and cafés. In winter or bad weather, the tour visits a lower station instead.'],
    ['Lunch and Lake Kawaguchi area', 'The group stops for lunch in the Fuji Five Lakes area, which is not included unless stated. Many tours stop at a viewpoint near Lake Kawaguchi, famous for its reflections of Mount Fuji on calm days. It is also a good area to buy local specialities, such as houtou noodles and Fuji-shaped sweets.'],
    ['Lake Ashi cruise', 'In Hakone, your clients board a sightseeing boat, often styled like a pirate ship, for a cruise across Lake Ashi, a crater lake formed by volcanic activity. On clear days, Mount Fuji rises behind the lake, and the red torii gate of Hakone Shrine can be seen standing in the water along the shore. The cruise lasts around 30 minutes.'],
    ['Hakone Ropeway and return', 'The Hakone Ropeway carries your clients over the Owakudani valley, where steam and sulphur rise from volcanic vents. The famous black eggs boiled in the hot springs are said to add seven years to your life. The ropeway may close when volcanic activity or winds are high. The group then returns to Tokyo by coach, or some tours return by bullet train, arriving in the evening.'],
  ],
  'Asakusa & Senso-ji Tour': [
    ['Meeting in Asakusa', 'Your clients meet their local guide near Asakusa station in north-east Tokyo, the most atmospheric old district of the city. The guide introduces the history of Asakusa, which was once Tokyo’s main entertainment district, known for its theatres, geisha houses and festivals. The area still preserves much of the old Edo-period atmosphere.'],
    ['Kaminarimon, the Thunder Gate', 'The tour begins at the Kaminarimon, the great outer gate of Senso-ji, with its huge red paper lantern and the statues of Fujin and Raijin, the gods of wind and thunder. It is one of the most famous landmarks in Tokyo and a perfect spot for photos. The guide explains the symbolism of the gate and the lantern.'],
    ['Nakamise-dori shopping street', 'Beyond the gate, Nakamise-dori is a lively street of around 90 small shops leading to the temple, some run by the same families for generations. Your clients can taste traditional snacks such as ningyo-yaki cakes filled with red bean paste and crispy rice crackers, and buy souvenirs like fans, kimonos and handcrafted items.'],
    ['Senso-ji Temple', 'At the end of the street stands Senso-ji, Tokyo’s oldest Buddhist temple, founded in 628. The guide shows your clients how to purify themselves with incense smoke and water, and how to pray at the main hall. They can also draw an omikuji fortune slip. The five-storey pagoda and the peaceful gardens nearby complete the visit.'],
    ['Asakusa back streets', 'The tour ends by exploring the quieter back streets of Asakusa, with traditional craft shops, small shrines and restaurants serving tempura, soba and sushi. On a clear day, the Tokyo Skytree can be seen across the Sumida River. Your clients can then take a river cruise, rent a kimono or enjoy lunch in the neighbourhood.'],
  ],
  'Shibuya & Harajuku Walk': [
    ['Meiji Shrine', 'The walk begins at the Meiji Shrine, dedicated to Emperor Meiji and Empress Shoken, set in a forest of around 100,000 trees in the middle of the city. Your clients pass through a giant wooden torii gate and walk along gravel paths to the shrine. The guide explains Shinto traditions, and if they are lucky, they may see a traditional wedding procession.'],
    ['Takeshita Street', 'Next, the group walks to Takeshita Street in Harajuku, the centre of Tokyo’s youth fashion and pop culture. The narrow street is packed with colourful boutiques, vintage shops and stalls selling rainbow candy floss and crêpes. It is lively and crowded, especially at weekends, and a fun contrast to the peace of the shrine.'],
    ['Omotesando', 'The guide then leads your clients along Omotesando, a wide avenue lined with zelkova trees, often called Tokyo’s Champs-Élysées. It is home to flagship stores of luxury brands in buildings designed by famous architects. The backstreets nearby, known as Ura-Harajuku, are full of independent designers, cafés and small galleries.'],
    ['Shibuya Crossing', 'The walk continues to Shibuya and its famous scramble crossing, where up to thousands of people cross from all directions at once when the lights change. Your clients can cross it themselves and then watch the scene from above, from a café or observation deck. The statue of Hachiko, the loyal dog, is right next to the crossing.'],
    ['Shibuya Sky or Center Gai', 'The tour ends in Shibuya, where your clients can explore Center Gai, a busy street of shops, arcades and restaurants, or visit an observation deck such as Shibuya Sky, which needs a separate ticket, for views over the city and, on clear days, Mount Fuji. The guide can recommend places to eat and shop before saying goodbye.'],
  ],
  'teamLab Planets': [
    ['Arrival in Toyosu', 'Your clients arrive at teamLab Planets in Toyosu, a short walk from Shin-Toyosu station on the Yurikamome line, at their timed entry slot. Tickets must be booked in advance and often sell out. They should arrive a few minutes early. Before entering, they store their shoes and bags in free lockers, as the visit is done barefoot.'],
    ['Water rooms', 'The first part of the museum takes your clients through spaces where they walk through knee-deep water, so shorts or trousers that can be rolled up are recommended. In the Infinite Crystal Universe, thousands of lights create an endless universe of stars around them, while in other rooms digital koi fish swim around their legs and turn into flowers when touched.'],
    ['Soft Black Hole and interactive spaces', 'Other installations play with the senses, such as the Soft Black Hole, where the floor gives way beneath visitors’ feet, and spaces where giant balls change colour when touched. The artworks respond to the people inside them, so the experience is different for everyone. It is fun for children and adults alike.'],
    ['Floating Flower Garden', 'In the Floating Flower Garden, thousands of real orchids hang from the ceiling and rise or lower as visitors move, creating a garden that surrounds them completely. The scent and colours are beautiful, and it is one of the most photographed spaces in the museum. Mirrors make the garden seem endless.'],
    ['Outdoor gardens and finish', 'The visit ends with the outdoor garden areas, including the Moss Garden, where egg-shaped objects glow and change colour, especially after dark. The visit takes around one and a half to two hours. After collecting their belongings, your clients can explore the Toyosu Market area or head to Odaiba nearby.'],
  ],

  // Lisbon
  'Tram 28 & Alfama Walk': [
    ['Meeting at Martim Moniz', 'Your clients meet their guide near Martim Moniz square, the starting point of the famous Tram 28. The guide explains the history of Lisbon’s trams, which have served the steep, narrow streets of the old city since the early 20th century. Boarding early helps avoid the long queues that form later in the day.'],
    ['Tram 28 ride', 'The yellow wooden tram climbs through the historic neighbourhoods of Graça and Alfama, squeezing through streets so narrow that it almost touches the buildings. Your clients see churches, viewpoints and colourful tiled façades pass by the windows. They should keep an eye on their belongings, as the tram can be very crowded.'],
    ['Miradouro da Graça and Senhora do Monte', 'The group gets off at the Graça viewpoints, which offer some of the best panoramic views of Lisbon, over the rooftops to São Jorge Castle and the Tagus River. It is a peaceful spot away from the crowds, and the guide points out the landmarks of the city below.'],
    ['Alfama streets and Lisbon Cathedral', 'The walk continues down through Alfama, the oldest district of Lisbon, which survived the great earthquake of 1755. Your clients wander through its labyrinth of narrow alleys and stairways, past laundry hanging from windows and small taverns. The guide then shows them the Sé, Lisbon Cathedral, founded in the 12th century.'],
    ['Miradouro de Santa Luzia', 'The tour ends at the Miradouro de Santa Luzia, a terrace decorated with blue azulejo tiles and bougainvillea, overlooking the rooftops of Alfama and the river. Nearby, the Miradouro das Portas do Sol offers another beautiful view. Your clients can then visit São Jorge Castle or enjoy lunch in one of the local restaurants.'],
  ],
  'Belém Monuments Tour': [
    ['Arrival in Belém', 'Your clients meet their guide in Belém, west of central Lisbon, on the banks of the Tagus River. This is where the great voyages of the Age of Discovery set out, including Vasco da Gama’s voyage to India in 1497. The guide introduces the history of the Portuguese explorers and how their wealth shaped the monuments of Belém.'],
    ['Jerónimos Monastery', 'The tour visits the Jerónimos Monastery, a masterpiece of the Manueline style, decorated with ropes, sea creatures and other maritime symbols carved in stone. Your clients explore the stunning two-storey cloister, one of the most beautiful in the world. The tomb of Vasco da Gama is in the church. The monastery is a UNESCO World Heritage Site.'],
    ['Monument to the Discoveries', 'By the river stands the Monument to the Discoveries, shaped like the prow of a ship, with statues of Henry the Navigator and other explorers, mapmakers and missionaries. In front of it, a huge compass rose with a map of the world shows the routes of the Portuguese voyages. A lift to the top gives views over Belém for an extra fee.'],
    ['Belém Tower', 'A short walk along the river leads to Belém Tower, a 16th-century fortress that guarded the entrance to Lisbon’s harbour and was the starting point for many voyages. With its decorated balconies and battlements, it is one of Lisbon’s most famous landmarks. Entry is not included, but the views from outside are beautiful.'],
    ['Pastéis de Belém tasting', 'The tour ends at the famous Pastéis de Belém bakery, which has been making custard tarts to a secret recipe from the monks of Jerónimos since 1837. Your clients taste one warm, sprinkled with cinnamon and sugar. They can stay on to visit the museums of Belém, such as the MAAT or the Coach Museum.'],
  ],
  'Sintra Palaces Day Trip': [
    ['Departure from Lisbon', 'Your clients are collected from a central meeting point or their hotel in Lisbon in the morning and travel to Sintra, around 40 minutes away. The guide introduces the history of Sintra, the summer retreat of the Portuguese royal family and aristocracy, with its lush hills, palaces and romantic gardens. The whole cultural landscape is a UNESCO World Heritage Site.'],
    ['Pena Palace', 'The highlight of the day is Pena Palace, perched on a hilltop and painted in bright yellow and red. Built in the 19th century by King Ferdinand II, it combines Gothic, Moorish and Manueline styles. Your clients explore the terraces and royal rooms, with views over the Sintra hills and, on clear days, the Atlantic Ocean.'],
    ['Pena Park', 'Surrounding the palace, Pena Park is a vast romantic garden with exotic trees from around the world, lakes, paths and follies. Your clients can walk through part of the park, which is cool and shaded even in summer. The guide shows them the viewpoints and explains how the king transformed the hillside.'],
    ['Sintra historic centre', 'The group then explores the historic centre of Sintra, with its narrow streets, cafés and the National Palace, known for its two huge white chimneys. Your clients have free time for lunch, which is not included, and can taste the local pastries, travesseiros and queijadas. The Quinta da Regaleira and the Moorish Castle are nearby for those who want more.'],
    ['Cabo da Roca and Cascais coast', 'In the afternoon, the tour drives to Cabo da Roca, the westernmost point of mainland Europe, with dramatic cliffs above the Atlantic. The return journey often follows the coast through the resort towns of Cascais and Estoril, with a stop for a walk by the sea. Your clients arrive back in Lisbon in the late afternoon.'],
  ],
  'Fado Dinner Show': [
    ['Arrival in Bairro Alto', 'Your clients arrive in the evening at a traditional fado house, or casa de fado, in the Bairro Alto or Alfama district. These historic neighbourhoods are the home of fado, and many of the restaurants are small, intimate spaces decorated with tiles, guitars and photographs of famous singers. Reservations are essential.'],
    ['Traditional Portuguese dinner', 'Dinner is a three-course Portuguese meal, often with dishes such as caldo verde soup, grilled fish, bacalhau (salt cod) or grilled meat, followed by a traditional dessert. Drinks are usually paid for separately, and Portuguese wines, such as vinho verde or reds from the Douro, are a perfect match.'],
    ['First fado set', 'The lights dim and the music begins. Fado, recognised by UNESCO as part of the world’s cultural heritage, is a melancholic, soulful song style often about longing, love and the sea, known as saudade. The singer is accompanied by a Portuguese guitar and a classical guitar. During the performance, silence is respected and service pauses.'],
    ['Between the sets', 'Between sets, dinner continues and your clients can chat and order drinks. The staff are usually happy to explain the meaning of the songs and the history of fado, from its origins in the poor neighbourhoods of Lisbon in the 19th century to its fame around the world through singers like Amália Rodrigues.'],
    ['Final performance', 'The evening continues with more sets, often by different singers, each with their own style. The show and dinner last around three hours. Afterwards, your clients can walk through the lively streets of Bairro Alto or take a taxi back to their hotel. Our team can arrange a transfer if they prefer.'],
  ],

  // Cape Town
  'Table Mountain Cableway': [
    ['Arrival at the lower cable station', 'Your clients arrive at the lower cable station on Tafelberg Road, at the foot of Table Mountain. With tickets booked in advance, they skip the ticket queue and join the boarding queue. The cableway closes in strong wind or low cloud, so it is best to go early on a clear day, and your clients should check the status on the morning of their visit.'],
    ['Rotating cable car', 'The modern cable car has a rotating floor that turns 360 degrees during the five-minute ride, so everyone gets a full view of the city, the Atlantic Ocean and Lion’s Head as they rise over the cliffs. The cable car climbs to around 1,067 metres above sea level. It is an exciting ride but very smooth and safe.'],
    ['Summit viewpoints', 'At the top, your clients follow the easy paths across the flat summit to viewpoints overlooking Cape Town, Table Bay, Robben Island, the Twelve Apostles mountain range and the Atlantic coastline. On clear days, they can see as far as Cape Point. Information boards explain the landmarks and the geology of the mountain.'],
    ['Fynbos and wildlife', 'Table Mountain is part of the Cape Floral Kingdom, one of the richest plant regions in the world, and the summit is covered with fynbos, the unique local vegetation, including proteas and ericas. Your clients may also spot dassies, small furry animals related to elephants, sunbathing on the rocks, as well as lizards and birds.'],
    ['Café and descent', 'Before heading down, your clients can enjoy a coffee or light meal at the summit café, with its views, and visit the shop. The cable car then takes them back to the lower station. A visit takes around two to three hours in total. Very fit visitors can hike up or down instead, although this takes several hours and should be done with a guide.'],
  ],
  'Cape Peninsula & Boulders Penguins': [
    ['Pickup and Atlantic coast', 'Your clients are collected from their hotel in the morning, and the tour follows the Atlantic coast south through Sea Point, Clifton and Camps Bay, with its white beaches and the Twelve Apostles mountains behind. The guide explains the history and geography of the Cape Peninsula along the way.'],
    ['Hout Bay and Chapman’s Peak Drive', 'The tour continues to Hout Bay, a fishing harbour where boats go out to see the Cape fur seals on Duiker Island, an optional extra. It then follows Chapman’s Peak Drive, one of the most spectacular coastal roads in the world, carved into the cliffs above the ocean, with plenty of stops for photos when conditions allow.'],
    ['Cape of Good Hope and Cape Point', 'The group enters the Table Mountain National Park and drives through fynbos landscapes where baboons, ostriches and antelope are often seen. Your clients visit the Cape of Good Hope, the south-western tip of Africa, and Cape Point, where they can walk or take the funicular up to the old lighthouse for sweeping ocean views.'],
    ['Lunch in Simon’s Town', 'Lunch, which is not included, is usually taken in Simon’s Town or a nearby fishing village on the False Bay coast. Simon’s Town is a historic naval town with Victorian buildings and a pretty harbour. Your clients can enjoy fresh seafood, such as fish and chips or calamari, before the final stop.'],
    ['Boulders Beach penguins and return', 'At Boulders Beach, boardwalks lead through the dunes to a colony of African penguins, which live and nest among the huge granite boulders. It is one of the few places in the world where people can see these endangered penguins so close. The tour returns to Cape Town via the False Bay coast, arriving back in the late afternoon.'],
  ],
  'Winelands Tasting Day': [
    ['Pickup and drive to the Winelands', 'Your clients are collected from their hotel in the morning and driven to the Cape Winelands, around 45 minutes to an hour from the city. The landscape of vineyards, oak trees and mountains is one of the most beautiful in South Africa. The guide explains the history of wine-making in the Cape, which began in the 17th century.'],
    ['Stellenbosch town', 'The first stop is Stellenbosch, South Africa’s second-oldest town, known for its oak-lined streets, Cape Dutch architecture and university. Your clients can walk through the historic centre, visit galleries and cafés, and learn about the town’s history. It is also the heart of the country’s most famous wine region.'],
    ['Stellenbosch wine estate tasting', 'Your clients visit a historic wine estate near Stellenbosch for a guided tasting of wines such as Chenin Blanc, Cabernet Sauvignon and Pinotage, a grape developed in South Africa. The guide or winemaker explains how the wines are made. Many estates also offer cheese, chocolate or olive pairings for an extra cost.'],
    ['Franschhoek valley', 'The tour continues over the mountains to Franschhoek, a charming village founded by French Huguenots in the 17th century, surrounded by mountains and vineyards. It is known as the food and wine capital of South Africa. Your clients have time for lunch, which is not included, at one of the many excellent restaurants.'],
    ['Boutique winery and return', 'The last stop is a boutique winery in the Franschhoek valley for a final tasting, often including sparkling wines made in the traditional method, known as Cap Classique. In the late afternoon, the group drives back to Cape Town, arriving at their hotels in the early evening. Wine purchases can often be shipped internationally.'],
  ],
  'Robben Island Tour': [
    ['Nelson Mandela Gateway', 'Your clients check in at the Nelson Mandela Gateway at the V&A Waterfront, where a small exhibition introduces the history of Robben Island. Tickets should be booked well in advance as they sell out quickly, and tours may be cancelled in bad weather. They should arrive at least 30 minutes before the ferry departs.'],
    ['Ferry across Table Bay', 'The ferry takes around 30 to 45 minutes to cross Table Bay to Robben Island, with beautiful views back to Table Mountain and the city. Your clients may see seals, dolphins and seabirds on the way. The crossing can be rough when the wind is strong, so those prone to seasickness should take precautions.'],
    ['Island bus tour', 'On arrival, your clients board a bus for a guided tour of the island. They see the limestone quarry where political prisoners, including Nelson Mandela, did hard labour, the house where Robert Sobukwe was held in isolation, the leper graveyard and the village where the staff lived. The guide explains the island’s long history as a place of banishment.'],
    ['Maximum-security prison', 'The tour continues on foot through the maximum-security prison, led by a former political prisoner who shares his own experiences. Your clients see the cell where Nelson Mandela spent 18 of his 27 years in prison. It is a moving and powerful experience, and a chance to learn about the struggle against apartheid first-hand.'],
    ['Return to the Waterfront', 'The ferry returns to the V&A Waterfront around three and a half to four hours after departure. Your clients can then explore the Waterfront’s shops, restaurants and the Zeitz MOCAA museum. Robben Island is a UNESCO World Heritage Site and one of the most important places to visit in South Africa.'],
  ],

  // Brașov
  'Bran Castle & Râșnov Fortress': [
    ['Departure from Brașov', 'Your clients are collected in Brașov in the morning and drive through the Transylvanian countryside towards the Bran Pass. The guide introduces the history of Transylvania, the Saxon settlers and the medieval towns that protected the region, and the real story of Vlad the Impaler, who inspired the Dracula legend.'],
    ['Râșnov Fortress', 'The first stop is Râșnov Fortress, a 13th-century peasant citadel built on a hill to protect villagers from invasions. Your clients walk up or take a small train to the fortress, where they explore the walls, towers and small houses, and hear the legend of the deep well dug by prisoners. The views over the Bârsa Land are spectacular.'],
    ['Bran village', 'The group then travels to Bran, a village at the foot of the castle, with stalls selling local cheese, handicrafts and Dracula souvenirs. Your clients can taste traditional smoked cheeses and other local products. The guide explains the importance of the Bran Pass as a trade route between Transylvania and Wallachia.'],
    ['Bran Castle', 'Bran Castle, perched on a rock above the village, is famous as “Dracula’s Castle”, although Bram Stoker never visited it. Your clients explore its narrow staircases, courtyards and rooms, which were the home of Queen Marie of Romania in the 1920s and 1930s. Exhibitions tell the stories of the castle, the queen and the vampire legend.'],
    ['Return to Brașov', 'After some free time for lunch in Bran, which is not included, the group returns to Brașov in the afternoon. Some tours stop at a viewpoint or a traditional village on the way. The whole trip takes around six hours, and it combines well with an old town walk in Brașov the same day or the next.'],
  ],
  'Old Town Walking Tour': [
    ['Council Square', 'Your clients meet their guide in Piața Sfatului, Council Square, the heart of Brașov’s medieval old town. The square is surrounded by colourful baroque buildings and the old Council House, which now houses the history museum. The guide introduces the history of the Saxon merchants who built and fortified the town from the 13th century.'],
    ['Black Church', 'A short walk away, the Black Church is the largest Gothic church in the region, built between the 14th and 15th centuries. It got its name after a great fire in 1689 blackened its walls. Inside, which requires a separate ticket, it houses a huge collection of Ottoman carpets and one of the largest organs in Europe.'],
    ['Rope Street', 'The walk continues to Strada Sforii, Rope Street, one of the narrowest streets in Europe, just over a metre wide in places. It was originally built as an access route for firefighters. Your clients can squeeze through for a fun photo, and the guide shares stories about daily life in the medieval town.'],
    ['Catherine’s Gate and the city walls', 'Next, the guide shows your clients Catherine’s Gate, the only surviving original gate of the medieval town, with its four small corner turrets, and the nearby Schei Gate. The walk continues along the old city walls and defensive towers, such as the White and Black Towers, with views over the old town rooftops.'],
    ['Brașov sign and Tâmpa Mountain', 'The tour ends near the foot of Tâmpa Mountain, with its Hollywood-style Brașov sign. Your clients can take the cable car to the top for panoramic views of the town and the Carpathian Mountains, which is not included. The walk takes around two hours, and the guide can recommend local restaurants for Transylvanian dishes.'],
  ],
  'Libearty Bear Sanctuary': [
    ['Departure from Brașov', 'Your clients are collected in Brașov and drive to the Libearty Bear Sanctuary near Zărnești, around 30 to 45 minutes away, at the foot of the Piatra Craiului Mountains. The guide explains how the sanctuary was founded in 2005 to rescue bears kept in cages at restaurants, circuses and private homes across Romania.'],
    ['Arrival and introduction', 'At the sanctuary, a local guide introduces the history of the project and the stories of some of the bears living there. Visits are only possible on guided tours at fixed times, which our team books in advance. The sanctuary covers around 70 hectares of oak and beech forest, where the bears can roam, swim and hibernate naturally.'],
    ['Walking the observation paths', 'Your clients follow the paths along the forest enclosures, where they can watch the brown bears playing, bathing in their pools and exploring the woods. More than 100 bears live here, so sightings are almost guaranteed. The guide explains how the bears are cared for and how they gradually learn to behave like wild bears again.'],
    ['Stories of the bears', 'Along the way, the guide shares the stories of individual bears, such as those that spent years in small cages before being rescued. It is a moving experience that raises awareness of animal welfare. Visitors cannot feed or touch the bears, and loud noises are discouraged to avoid disturbing them.'],
    ['Return to Brașov', 'After the visit, which lasts around an hour and a half, your clients return to Brașov. Some tours combine the sanctuary with a visit to Zărnești Gorge or Bran Castle. The whole trip takes around four hours. The sanctuary is closed on some days and during certain periods, so our team confirms availability when booking.'],
  ],
  'Peleș Castle Day Trip': [
    ['Departure from Brașov', 'Your clients are collected in Brașov in the morning and drive through the Prahova Valley towards Sinaia, around an hour away, with the Bucegi Mountains towering above the road. The guide introduces the history of the Romanian royal family and how Sinaia became their summer residence in the late 19th century.'],
    ['Peleș Castle', 'Peleș Castle, built for King Carol I between 1873 and 1914, is one of the most beautiful castles in Europe, in the neo-Renaissance style with wooden details. Your clients take a guided tour of the richly decorated rooms, with carved wood, stained glass, weapons collections and paintings. It was the first castle in Europe to have electricity.'],
    ['Pelișor Castle and gardens', 'Next to Peleș, the smaller Pelișor Castle was built for the future King Ferdinand and Queen Marie, and decorated in the Art Nouveau style. Your clients can visit it if open, or stroll through the terraced gardens with statues and fountains overlooking the forests. Photography inside the castles may require a separate fee.'],
    ['Sinaia Monastery', 'In the town of Sinaia, your clients visit Sinaia Monastery, founded in the 17th century and named after St Catherine’s Monastery on Mount Sinai. It has two churches, the old one with beautiful painted walls and the larger one built in the 19th century. The monastery gave its name to the town that grew around it.'],
    ['Lunch and return', 'Your clients have time for lunch in Sinaia, which is not included, where local restaurants serve traditional Romanian food. Some tours stop at a viewpoint in the Bucegi Mountains or visit the town of Bușteni on the way back. They arrive back in Brașov in the late afternoon, around eight hours after departure.'],
  ],

  // Sydney
  'Sydney Opera House Tour': [
    ['Meeting at the Welcome Centre', 'Your clients arrive at the Welcome Centre on the lower concourse of the Sydney Opera House at Bennelong Point. Tours run throughout the day in several languages, and they should arrive around 15 minutes before their tour starts. The guide gives an introduction to the building, a UNESCO World Heritage Site and one of the most famous buildings of the 20th century.'],
    ['The story of the design', 'The guide explains the story of the Danish architect Jørn Utzon, who won the international design competition in 1957, and the challenges of building the famous sail-shaped roofs. Utzon left the project before its completion, and the building was finally opened in 1973. Your clients learn how the shells were built using precast concrete sections.'],
    ['Concert Hall', 'The tour takes your clients inside the Concert Hall, the largest venue in the building, with its huge organ and wooden interiors designed for world-class acoustics. Depending on rehearsals, they may watch from the seats or the foyers. The views through the glass walls of the foyers across the harbour are spectacular.'],
    ['Joan Sutherland Theatre and the Utzon Room', 'The tour continues to the Joan Sutherland Theatre, home to opera and ballet, and the Utzon Room, the only interior designed by Utzon himself, with a large tapestry he created. Access to each venue depends on performances and rehearsals on the day, so the exact route may change.'],
    ['Harbour views and finish', 'The tour ends after around an hour back at the Welcome Centre. Your clients can then walk around the building’s exterior and the forecourt, with views of the Harbour Bridge, or have a drink at one of the harbourside bars. Our team can also book a performance for the evening, from opera to concerts.'],
  ],
  'Harbour Bridge Climb': [
    ['Check-in at The Rocks', 'Your clients check in at the BridgeClimb base in The Rocks, the historic area at the southern end of the Harbour Bridge, around 15 to 30 minutes before their climb. They complete a health declaration and a breathalyser test, as climbers must not be under the influence of alcohol. Minimum age and health requirements apply.'],
    ['Safety briefing and gearing up', 'After a safety briefing, your clients put on a special climb suit and are fitted with a harness, radio headset and safety equipment. Everything is attached to the climber, including glasses and hats, and personal items such as phones and cameras are not allowed, for the safety of the traffic below. The team practises on a climb simulator.'],
    ['The climb begins', 'Attached to a static line, your clients follow their climb leader through the bridge structure, up ladders and along the catwalks to the arches. The climb is steady and suitable for most people with a reasonable level of fitness. The climb leader shares stories of the bridge’s construction, completed in 1932, through the headset.'],
    ['At the summit', 'At the summit, 134 metres above the harbour, your clients enjoy 360-degree views of Sydney, including the Opera House, the harbour, the city skyline and, on clear days, the Blue Mountains. The climb leader takes photos of the group, with one group photo included. Twilight and night climbs offer a different atmosphere.'],
    ['Descent and certificate', 'After the summit, the group climbs back down to the base, where your clients change out of their suits. They receive a climb certificate and can buy more photos. The whole experience takes around three and a half hours. It is a highlight of any trip to Sydney and a popular choice for special occasions.'],
  ],
  'Blue Mountains Day Trip': [
    ['Departure from Sydney', 'Your clients are collected from their hotel or a central meeting point in Sydney in the morning, and drive west to the Blue Mountains, around two hours away. The guide explains how the mountains get their blue haze from the oil released by the eucalyptus trees. The Greater Blue Mountains Area is a UNESCO World Heritage Site.'],
    ['Featherdale Wildlife Park', 'On selected tours, the first stop is Featherdale Wildlife Park on the way to the mountains, where your clients can meet Australian animals such as kangaroos, wallabies, koalas, wombats and emus. They can hand-feed the kangaroos and take photos close to the koalas. It is especially popular with families.'],
    ['Echo Point and the Three Sisters', 'In Katoomba, your clients visit Echo Point, the most famous lookout in the Blue Mountains, with views of the Three Sisters rock formation and the Jamison Valley. The guide shares the Aboriginal legend of the Three Sisters. There are short walks from here, such as the path to the Honeymoon Bridge on the first sister.'],
    ['Scenic World', 'Next, your clients visit Scenic World, where they ride the Scenic Railway, the steepest passenger railway in the world, down into the rainforest, walk along the boardwalk among ancient tree ferns, and ride the Scenic Skyway, a glass-floored cable car over the valley, with views of the Katoomba Falls and the Three Sisters.'],
    ['Leura village and return', 'Many tours stop at Leura, a charming mountain village with galleries, cafés and gardens, for lunch or coffee, which is not included. The group then drives back to Sydney, and some tours return by ferry along the Parramatta River. Your clients arrive back in the city in the early evening, around nine hours after departure.'],
  ],
  'Bondi to Coogee Coastal Walk': [
    ['Bondi Beach', 'Your clients meet their guide at Bondi Beach, Australia’s most famous beach, with its golden sand, surfers and lifeguards. The guide introduces the history of Bondi and the local surf culture. Before setting off, your clients can see the Bondi Icebergs ocean pool at the southern end of the beach, one of the most photographed spots in Sydney.'],
    ['Tamarama', 'The walk follows a clifftop path along the coast, with spectacular views of the ocean and sandstone cliffs. The first stop is Tamarama, a small, pretty beach known as “Glamarama” for its popularity with the fashionable crowd. In spring, the Sculpture by the Sea exhibition displays artworks along this part of the walk.'],
    ['Bronte Beach and ocean pool', 'The path continues to Bronte Beach, with its large park and rock pool, the Bronte Baths, cut into the rocks at the edge of the ocean. It is a great spot for a swim or a coffee. The guide explains how Sydney’s ocean pools let people swim safely in the sea, even when the waves are big.'],
    ['Waverley Cemetery and Clovelly', 'The walk passes Waverley Cemetery, perched on the cliffs, with its ornate graves of famous Australians and sweeping ocean views, before reaching Clovelly, a long, narrow bay that is perfect for snorkelling, as the water is calm and full of fish. It is a peaceful stop on the walk.'],
    ['Coogee Beach', 'The walk ends at Coogee Beach, a lively beach with cafés, restaurants and the historic Wylie’s Baths and McIver’s Ladies Baths ocean pools. The walk is around six kilometres and takes about three hours with stops. Your clients can relax on the beach, have a swim or take a bus or taxi back to the city.'],
  ],
}
