import type { Itinerary } from './types'

// Full itineraries: London, New York, Rajasthan, Rome, Marrakech, Paris.
export const west: Record<string, Itinerary> = {
  // London
  'London Eye Fast Track': [
    ['Arrival on the South Bank', 'Your clients arrive at the London Eye on the South Bank of the Thames, a short walk from Waterloo or Westminster stations. They should arrive around 30 minutes before their time slot and head to the fast-track entrance with their tickets. The area around the Eye is lively, with street performers, cafés and views across the river to the Houses of Parliament.'],
    ['4D cinema experience', 'Before boarding, your clients can enjoy the short 4D cinema experience, which is included with the ticket. The film follows a young girl on a journey around London, with 3D images and special effects such as wind, bubbles and snow. It lasts only a few minutes and is especially popular with children, making a fun warm-up before the ride.'],
    ['Fast-track boarding', 'With fast-track entry, your clients skip the main queue and go straight to a dedicated boarding line, which can save a lot of time in summer and at weekends. After a quick security check, they step into one of the 32 glass capsules. The wheel moves slowly and continuously, so boarding is easy, and staff help anyone who needs assistance.'],
    ['The rotation', 'A full rotation takes around 30 minutes and rises to 135 metres above the Thames. On a clear day, your clients can see up to 40 kilometres, with views of Big Ben, the Houses of Parliament, Buckingham Palace, St Paul’s Cathedral and the Shard. Interactive guides in the capsule help them identify the landmarks. There is room to walk around and take photos from every side.'],
    ['Back on the river', 'After the ride, your clients step out on the South Bank, which is ideal for continuing their day. They can walk along the river to the Sea Life aquarium, the Southbank Centre and Tate Modern, or cross Westminster Bridge to Parliament Square and Westminster Abbey. River cruises also leave from the pier right next to the Eye.'],
  ],
  'Tower of London & Crown Jewels': [
    ['Arrival at Tower Hill', 'Your clients arrive at the Tower of London, next to Tower Hill underground station and a short walk from Tower Bridge. With their tickets booked in advance, they head to the main entrance. It is best to arrive at opening time and go to the Crown Jewels first, before the queues build up in the late morning, especially in summer.'],
    ['Yeoman Warder tour', 'The Yeoman Warders, known as Beefeaters, lead free tours from near the entrance throughout the day. Dressed in their famous uniforms, they tell stories of the Tower’s history, from royal prisoners and executions to escapes and legends, with plenty of humour. The tour lasts around an hour and is one of the highlights of a visit. It may not run in bad weather.'],
    ['Crown Jewels in the Jewel House', 'Inside the Jewel House, your clients see the Crown Jewels, the most famous collection of royal regalia in the world, still used in coronations. Highlights include the Imperial State Crown and the Sovereign’s Sceptre with the Cullinan I diamond, one of the largest cut diamonds in the world. A moving walkway takes visitors past the crowns, and they can go round again.'],
    ['White Tower', 'The White Tower, built by William the Conqueror in the 1070s, is the oldest part of the Tower. Inside, the Royal Armouries display suits of armour, including those made for Henry VIII, as well as weapons and the Line of Kings, one of the oldest museum displays in the world. There are many stairs, and the views from the windows over the grounds are excellent.'],
    ['Walls, ravens and Tower Green', 'Finally, your clients can walk along the medieval walls, visit the Bloody Tower and see the ravens, which legend says must stay at the Tower to protect the kingdom. Tower Green marks the spot where several famous executions took place, including Anne Boleyn. A full visit takes around three hours, and Tower Bridge is right next door for those who want to continue.'],
  ],
  'West End Show': [
    ['Arrival in Theatreland', 'Your clients arrive in the West End in the early evening, where theatres cluster around Leicester Square, Covent Garden and Shaftesbury Avenue. It is worth arriving early to enjoy the atmosphere, as the streets fill with theatregoers, bright signs and street performers. Many restaurants in the area offer pre-theatre menus served quickly before the show.'],
    ['Collecting tickets and finding seats', 'Tickets are usually sent electronically or collected at the box office, and our team confirms how they will be issued. Your clients should arrive at the theatre around 30 minutes before the show starts, as there may be a bag check. Many West End theatres are historic buildings with steep stairs and narrow seats, so our team can advise on the best seating options.'],
    ['First act', 'The show begins, usually at 7:30pm, with matinees on some afternoons. Whether it is a long-running musical or a new play, the West End offers world-class performances, sets and music. Photography and recording are not allowed during the performance. Latecomers may have to wait for a suitable break before they are seated, so arriving on time is important.'],
    ['Interval', 'Most shows have an interval of around 20 minutes. Your clients can stretch their legs, buy a drink or ice cream at the bar, or pick up a programme and souvenirs. Drinks can often be ordered before the show so they are ready at the interval, avoiding the queue. It is a good moment to enjoy the historic interiors of the theatre.'],
    ['Second act and after the show', 'After the second act and the curtain call, the show ends at around 10pm to 10:30pm, depending on the production. Your clients can then enjoy a late dinner or drinks in Covent Garden or Soho. The West End is well connected by the Underground and night buses, and our team can arrange a transfer back to the hotel if needed.'],
  ],
  'Warner Bros. Studio Tour – Harry Potter': [
    ['Coach from central London', 'Your clients meet the coach at a central London departure point, usually near Victoria or Baker Street, and travel to the Warner Bros. Studios in Leavesden, around an hour away depending on traffic. On board, they may watch Harry Potter content to get into the mood. The coach and entry times are coordinated, so arriving on time for departure is essential.'],
    ['Entrance and the Great Hall', 'After a short introductory film, the doors open onto the Great Hall of Hogwarts, the original set used in the films, with its long tables, stone floors and costumes worn by the actors. It is one of the most exciting moments of the tour, and a great photo opportunity. From here, visitors explore the rest of the studio at their own pace.'],
    ['Sets, props and costumes', 'The first soundstage is filled with original sets, including Dumbledore’s office, the Gryffindor common room, the Potions classroom and the Ministry of Magic. Your clients see hundreds of props and costumes up close and learn how the special effects were created. Interactive areas let them try broomstick flying in front of a green screen, at an extra cost.'],
    ['Platform 9¾ and the Backlot', 'Next, your clients step onto Platform 9¾ and board the Hogwarts Express. The Backlot café is the place to try Butterbeer, before exploring outdoor sets such as Privet Drive, the Knight Bus and Hogwarts Bridge. Afterwards, the tour continues with the creature effects department and the models and concept art used in the films.'],
    ['Diagon Alley and the Hogwarts model', 'The highlight for many fans is Diagon Alley, with its crooked shopfronts including Ollivanders and Gringotts. The tour ends with the huge, detailed model of Hogwarts Castle, used for exterior shots in the films. After a visit to the gift shop, your clients return to central London by coach. The whole trip takes around seven hours.'],
  ],

  // New York
  'Statue of Liberty & Ellis Island': [
    ['Security and boarding at Battery Park', 'Your clients arrive at Battery Park in Lower Manhattan and go through airport-style security before boarding the ferry. It is best to take one of the first departures of the day to avoid long queues. The ferry is the only official way to reach the islands, and it gives excellent views of the Lower Manhattan skyline as it leaves the pier.'],
    ['Crossing New York Harbor', 'The ferry crosses New York Harbor towards Liberty Island, passing close to the Statue of Liberty. Your clients should head to the upper deck or the right-hand side of the boat for the best photos as they approach. The ride takes around 15 minutes, and the views back towards Manhattan and the Brooklyn Bridge are spectacular.'],
    ['Liberty Island', 'On Liberty Island, your clients can walk around the Statue of Liberty and learn its story with the included audio guide. The statue, a gift from France, was dedicated in 1886 and has become a symbol of freedom around the world. The Statue of Liberty Museum on the island displays the original torch and tells the story of its design and construction.'],
    ['Ellis Island National Museum of Immigration', 'The ferry continues to Ellis Island, the gateway for more than 12 million immigrants between 1892 and 1954. In the museum, your clients walk through the Great Hall, where newcomers waited for inspection, and see photographs, personal belongings and stories of families who arrived here. Many visitors search the passenger records for their own ancestors.'],
    ['Return to Manhattan', 'After visiting Ellis Island, your clients take the ferry back to Battery Park. The whole trip takes around four hours, depending on how long they spend at each island. From Battery Park, they can walk to Wall Street, the 9/11 Memorial and One World Observatory. Access to the pedestal or crown needs a separate ticket booked well in advance.'],
  ],
  'Top of the Rock Observation Deck': [
    ['Arrival at Rockefeller Center', 'Your clients arrive at Rockefeller Center in Midtown Manhattan and enter the Top of the Rock at 30 Rockefeller Plaza, with a timed ticket. Before going up, they can see the famous Rockefeller Plaza, with its gold Prometheus statue, flags and, in winter, the ice rink and the huge Christmas tree. Sunset slots are the most popular and sell out quickly.'],
    ['Exhibits and the Sky Shuttle', 'Inside, a short exhibition tells the story of Rockefeller Center and the construction of this Art Deco landmark during the 1930s, including the famous photograph of workers eating lunch on a steel beam. Your clients then ride the Sky Shuttle lift, which has a glass ceiling with a light show, to the 67th floor in less than a minute.'],
    ['67th and 69th floor decks', 'The lower observation decks offer indoor and outdoor viewing areas behind glass panels. From here, your clients get a clear view of the Empire State Building to the south, with the Chrysler Building, One World Trade Center and the rivers on either side. It is one of the best views of the Empire State Building in the city.'],
    ['70th floor open-air deck', 'The top deck, on the 70th floor, is completely open with no glass, giving uninterrupted 360-degree views. To the north, Central Park stretches out like a green rectangle between the buildings, which is a view the Empire State Building cannot offer. Your clients can stay as long as they like, and the lights of the city at night are unforgettable.'],
    ['Rockefeller Center and Fifth Avenue', 'After coming down, your clients can explore Rockefeller Center’s shops, restaurants and gardens, or visit Radio City Music Hall and St Patrick’s Cathedral nearby. Fifth Avenue’s flagship stores are just around the corner. The visit takes around one to two hours, making it easy to combine with a day of Midtown sightseeing.'],
  ],
  'Broadway Show': [
    ['Arrival in the Theater District', 'Your clients arrive in the Theater District around Times Square in the early evening. The streets fill with theatregoers, bright billboards and marquees, creating a unique atmosphere. Many restaurants on Restaurant Row, West 46th Street, serve pre-theatre dinner quickly, and it is worth booking a table in advance on busy nights.'],
    ['Entering the theatre', 'Tickets are usually sent electronically, and our team confirms how they will be issued. Your clients should arrive at least 30 minutes before the show, as there is a bag check at the entrance. Ushers help them find their seats and hand out the Playbill, the famous programme that has become a souvenir. Many theatres are historic and beautifully decorated.'],
    ['Act one', 'The performance begins, usually at 7pm or 8pm, with matinees on some days. Broadway shows feature top performers, live orchestras and spectacular sets. Photography and recording are strictly forbidden during the performance. Latecomers may have to wait until a suitable moment to be seated, so arriving on time is important.'],
    ['Intermission', 'Most shows have an intermission of around 15 minutes. Your clients can buy drinks and snacks at the bar, often in souvenir cups they can take back to their seats, or browse show merchandise. Queues for the restrooms can be long, so it is worth going early in the intermission. It is also a chance to look around the theatre.'],
    ['Curtain call and after the show', 'After the second act and the curtain call, many shows let the audience take photos of the stage. Around the stage door, fans sometimes wait to meet the cast. The evening can continue with dinner or drinks in Times Square or Hell’s Kitchen. Our team can advise on current shows, seating and family-friendly options when booking.'],
  ],
  'Central Park Bike Tour': [
    ['Meeting point and bike fitting', 'Your clients meet their guide at a bike shop near the south end of Central Park, usually around Columbus Circle or 59th Street. They are fitted with a bike and helmet, and the guide gives a short safety briefing. The tour follows the park’s paved drives and paths at a relaxed pace, so it is suitable for most riders, including families with older children.'],
    ['Strawberry Fields', 'The first stop is Strawberry Fields, a peaceful garden created in memory of John Lennon, who lived in the Dakota building across the street. The famous black-and-white Imagine mosaic is a place where fans leave flowers and play music. The guide shares the story of Lennon’s life in New York and the design of the memorial.'],
    ['Bethesda Terrace and Fountain', 'Next, the tour reaches Bethesda Terrace, the elegant heart of Central Park, with its sweeping staircases, decorated arcade and the Angel of the Waters fountain. It overlooks the lake and has appeared in many films and TV shows. Musicians often play in the arcade under the terrace, which has a beautiful tiled ceiling.'],
    ['Bow Bridge and the Lake', 'A short ride away, Bow Bridge is a cast-iron bridge over the lake and one of the most romantic spots in the park, with views of the city skyline over the trees. Rowing boats glide across the water in the warmer months. The guide explains how Central Park was designed in the 19th century to create natural landscapes in the middle of the city.'],
    ['More park highlights and return', 'Depending on the route, the tour may continue past the Jacqueline Kennedy Onassis Reservoir, Belvedere Castle, the Great Lawn or the Conservatory Garden. The guide shares stories and facts along the way and stops for photos. The tour returns to the starting point after around two hours, and your clients can keep exploring the park or head to Fifth Avenue.'],
  ],

  // Rajasthan
  'Amber Fort & Jaipur City Tour': [
    ['Hotel pickup and Hawa Mahal', 'Your clients are collected from their Jaipur hotel in the morning by their private car, driver and guide. The first stop is the Hawa Mahal, the Palace of Winds, with its honeycomb façade of 953 small windows. It was built so royal women could watch the street life without being seen. The best photos are taken from across the street in the soft morning light.'],
    ['Amber Fort', 'The car then drives to Amber Fort, about 11 kilometres north of the city, set on a hill above Maota Lake. Your clients walk up or take a jeep to the main gate, and the guide leads them through courtyards and halls built of pale yellow and pink sandstone and marble. The fort combines Rajput and Mughal styles, with painted gateways and views over the surrounding hills.'],
    ['Sheesh Mahal, the Mirror Palace', 'Inside Amber Fort, the Sheesh Mahal is decorated with thousands of tiny mirrors set into the walls and ceilings, so that a single candle could light up the whole room like a starry sky. The guide explains the life of the Maharajas who lived here, as well as the fort’s clever cooling and water systems. The visit takes around two hours.'],
    ['City Palace', 'Back in the city, the City Palace is still home to the royal family of Jaipur. Your clients explore its courtyards, gateways decorated with peacock motifs, and museum collections of royal costumes, textiles and weapons. The guide points out the Chandra Mahal, where the royal family lives, and the huge silver urns in the Diwan-i-Khas.'],
    ['Jantar Mantar and return', 'Next door, Jantar Mantar is an astronomical observatory built in the early 18th century, with giant stone instruments that measure time and track the stars, including the world’s largest stone sundial. It is a UNESCO World Heritage Site. After the visit, your clients can explore the bazaars or return to their hotel, around six hours after pickup.'],
  ],
  'Lake Pichola Sunset Boat Ride': [
    ['Arrival at the jetty', 'Your clients arrive at the boat jetty near the City Palace in Udaipur in the late afternoon, around an hour before sunset. Tickets are checked at the entrance, and life jackets are provided on board. The waterfront is lively, with views of the palace walls rising above the lake. It is a relaxed experience suitable for all ages.'],
    ['City Palace from the water', 'As the boat sets off, your clients see the City Palace from the water, its long façade of balconies, towers and domes stretching along the eastern shore. The palace complex was built over several centuries by the Maharanas of Mewar and is the largest in Rajasthan. From the lake, its size and position above the water are most impressive.'],
    ['Lake Palace', 'The boat then passes the Lake Palace, the white marble palace that seems to float in the middle of the lake. Built in the 18th century as a royal summer retreat, it is now a luxury hotel, the Taj Lake Palace, and only guests can go ashore. It famously appeared in the James Bond film Octopussy, and it is one of the most photographed views in India.'],
    ['Jag Mandir island', 'On selected cruises, the boat stops at Jag Mandir, an island palace with gardens, carved elephants and marble pavilions. Your clients can walk around the island for a short while and enjoy views back towards the city. It is said that the young Prince Khurram, later Shah Jahan who built the Taj Mahal, stayed here and found inspiration.'],
    ['Sunset over the Aravalli Hills', 'As the sun sets behind the Aravalli Hills, the lake and the palaces glow gold and pink, and the ghats and havelis along the shore begin to light up. It is one of the most romantic moments in Rajasthan. The boat returns to the jetty around dusk, and your clients can have dinner at a rooftop restaurant with lake views.'],
  ],
  'Desert Camp & Camel Safari': [
    ['Arrival at the camp', 'Your clients travel from Jaisalmer to the desert camp near the Sam Sand Dunes, around 40 kilometres west of the city, in the afternoon. Transfers from Jaisalmer are arranged separately. On arrival, they are welcomed with a traditional Rajasthani greeting and tea, and shown to their tent, which usually has proper beds and an attached bathroom.'],
    ['Camel safari to the dunes', 'In the late afternoon, your clients set off on a camel safari across the golden dunes of the Thar Desert. Each camel is led by a local camel handler, and the pace is gentle. The ride gives a sense of how people have travelled through the desert for centuries. Jeep safaris are also available at extra cost for those who prefer a faster ride.'],
    ['Sunset over the Thar', 'The camels stop on the dunes as the sun sets, turning the sand deep orange and red. Your clients can walk on the dunes, take photos and enjoy the vast silence of the desert. It is one of the most memorable experiences in Rajasthan, and the light at this time of day is perfect for photographs.'],
    ['Folk music, dance and dinner', 'Back at the camp, the evening continues around a campfire with Rajasthani folk music and dance performances, often including the Kalbelia dance and skilled local musicians. Dinner is a traditional Rajasthani buffet, with dishes such as dal baati churma, ker sangri and freshly made rotis. Drinks are paid for separately.'],
    ['Night under the stars and breakfast', 'With little light pollution, the night sky over the desert is full of stars, and your clients can enjoy the peace before retiring to their tent. In the morning, they can wake early for sunrise over the dunes before breakfast is served. After breakfast, they check out and return to Jaisalmer to continue their journey.'],
  ],
  'Mehrangarh Fort Walk': [
    ['Arrival at Mehrangarh Fort', 'Your clients arrive at Mehrangarh Fort, which rises around 120 metres above Jodhpur on a rocky hill. They collect their tickets and audio guide at the entrance. A lift can take visitors up to the upper levels, although walking up through the gates gives a better sense of the fort’s defences. It is best to visit in the morning before the heat.'],
    ['The seven gates', 'The road into the fort passes through a series of gates built to celebrate victories and defend the fort. The Jai Pol, or Victory Gate, and the Loha Pol, with iron spikes to stop elephant attacks, are highlights. Near the Loha Pol, handprints on the wall mark the spot where royal women performed sati. The audio guide explains the history of each gate.'],
    ['Palaces and museum galleries', 'Inside, your clients explore palaces with finely carved sandstone windows and courtyards. The museum galleries display royal palanquins, elephant howdahs, weapons, paintings, costumes and cradles. The Phool Mahal, or Palace of Flowers, and the Sheesh Mahal, the Mirror Palace, are among the most beautiful rooms in Rajasthan.'],
    ['Ramparts and views of the Blue City', 'From the ramparts, lined with old cannons, your clients look down on the blue houses of the old city of Jodhpur, traditionally painted to keep them cool and to mark the homes of Brahmins. The view over the city and the desert beyond is spectacular, especially in the soft light of the morning.'],
    ['Chamunda Mata Temple and Jaswant Thada', 'At the far end of the fort stands the Chamunda Mata Temple, dedicated to the goddess of the royal family. After the visit, many visitors continue to Jaswant Thada, a white marble memorial nearby, with lovely views back towards the fort. The whole visit takes around three hours, and your clients can finish with a walk through the Sardar Market.'],
  ],

  // Rome
  'Colosseum & Roman Forum': [
    ['Meeting point and skip-the-line entry', 'Your clients meet their guide near the Colosseum metro station, where headsets are handed out so everyone can hear clearly. With skip-the-line entry, they avoid the long ticket queues and pass through security more quickly. Passports or ID may be required, as Colosseum tickets are named. The guide gives an introduction to ancient Rome before entering.'],
    ['Inside the Colosseum', 'Inside the Colosseum, completed in 80 AD and able to hold around 50,000 spectators, your clients walk along the lower tier and look down into the arena. The guide explains how the gladiator fights and animal hunts were organised, how spectators were seated by social class, and how the complex network of tunnels and lifts under the arena worked.'],
    ['Arch of Constantine', 'Leaving the Colosseum, the group passes the Arch of Constantine, the largest surviving Roman triumphal arch, built in 315 AD to celebrate the Emperor Constantine’s victory. The guide points out the carvings, some reused from earlier monuments. The arch stands at the start of the ancient triumphal route that led into the city.'],
    ['Palatine Hill', 'The tour climbs Palatine Hill, where, according to legend, Romulus founded Rome, and where the emperors later built their palaces. Your clients walk among the ruins of the imperial residences, gardens and stadium. From the top, there are wonderful views over the Roman Forum and the Circus Maximus, where chariot races were held.'],
    ['Roman Forum', 'The tour ends in the Roman Forum, the centre of political, religious and commercial life in ancient Rome. Your clients walk along the Via Sacra past the Temple of Saturn, the House of the Vestal Virgins, the Senate House and the place where Julius Caesar was cremated. The tour lasts around three hours, and your clients can stay on to explore.'],
  ],
  'Vatican Museums & Sistine Chapel': [
    ['Meeting point and entry', 'Your clients meet their guide near the entrance to the Vatican Museums, a short walk from the Ottaviano metro station. With reserved skip-the-line entry, they avoid the long queues that can stretch along the Vatican walls. After security, headsets are handed out. Shoulders and knees must be covered, as the tour ends in a sacred site.'],
    ['Pinecone Courtyard and classical sculpture', 'The tour starts in the Cortile della Pigna, with its giant bronze pinecone, where the guide explains the Sistine Chapel frescoes before going in, since talking is not allowed inside the chapel. Your clients then see masterpieces of classical sculpture, such as the Laocoön group and the Belvedere Torso, which inspired Michelangelo.'],
    ['Gallery of Tapestries and Gallery of Maps', 'The route continues through long galleries, including the Gallery of Tapestries, with works designed by Raphael’s school, and the Gallery of Maps, where 40 large painted maps show the regions of Italy in the 16th century under a richly decorated golden ceiling. It is one of the most beautiful corridors in the world.'],
    ['Raphael Rooms', 'Next come the Raphael Rooms, four rooms painted by Raphael and his workshop for Pope Julius II. The most famous fresco, The School of Athens, shows the great philosophers of ancient Greece, with Plato and Aristotle at its centre, and Michelangelo depicted as Heraclitus. The guide explains the stories and symbolism in each room.'],
    ['Sistine Chapel', 'The tour ends in the Sistine Chapel, where Michelangelo painted the ceiling between 1508 and 1512, including the famous Creation of Adam, and later The Last Judgement on the altar wall. Photography is not allowed. Your clients can stay as long as they like. Some tours exit directly into St Peter’s Basilica, depending on access on the day.'],
  ],
  'Trastevere Food Tour': [
    ['Meeting in Trastevere', 'Your clients meet their food guide in the late afternoon in the heart of Trastevere, near the Piazza di Santa Maria. This charming neighbourhood of cobbled streets, ivy-covered buildings and family-run trattorias is one of the most authentic in Rome. The guide checks any dietary needs and explains the plan for the evening.'],
    ['Supplì and street food', 'The first stop is usually a local shop for supplì, fried rice balls filled with tomato sauce and mozzarella, a Roman street food classic. Your clients may also taste pizza al taglio, Roman pizza sold by the slice. The guide explains the history of Roman food and how it developed from simple, local ingredients.'],
    ['Cured meats, cheese and wine', 'Next, the group visits a traditional deli or wine bar to taste Italian cured meats, such as prosciutto and mortadella, and cheeses like pecorino romano, with local wine. The guide explains how these products are made and which regions they come from. It is a relaxed, sociable stop where your clients can ask questions.'],
    ['Roman pasta dinner', 'The main stop is a trattoria where your clients sit down to try classic Roman pasta dishes, such as cacio e pepe, carbonara or amatriciana, often served with wine. The guide explains the differences between them and the strict rules Romans follow for each recipe. Portions are generous, so it is best to arrive hungry.'],
    ['Gelato and a walk by the river', 'The tour ends with authentic gelato from an artisan gelateria, and the guide shares tips on how to spot good gelato. The evening finishes around four hours after it began, near the Tiber River. Your clients can then stroll across the Ponte Sisto into the historic centre or stay in Trastevere for a drink.'],
  ],

  // Marrakech
  'Medina & Souks Guided Walk': [
    ['Koutoubia Mosque', 'Your clients meet their licensed local guide near the Koutoubia Mosque, the largest mosque in Marrakech, whose 77-metre minaret has been the city’s landmark since the 12th century. Non-Muslims cannot enter, but the guide explains its history and architecture from the gardens outside. It is a good starting point to understand the layout of the city.'],
    ['Bahia Palace', 'The walk continues to the Bahia Palace, built in the late 19th century for a powerful grand vizier. Your clients explore its courtyards, gardens and rooms decorated with painted cedar ceilings, zellige tilework and carved stucco. The guide explains the life of the palace and its many wives and concubines. Entrance fees are paid separately.'],
    ['Mellah and spice market', 'Next, the guide leads the group through the Mellah, the old Jewish quarter, with its spice market, small shops and historic synagogue. Your clients see stalls piled with spices, herbs, dried fruit and traditional remedies, and the guide explains how they are used in Moroccan cooking and medicine.'],
    ['The souks', 'The heart of the walk is the maze of souks north of the main square, where each area specialises in a trade: leather, metalwork, carpets, lanterns, spices, dyes and slippers. With a guide, your clients can explore without getting lost, see craftsmen at work and learn how to bargain. There is no obligation to buy anything.'],
    ['Jemaa el-Fna', 'The walk ends at Jemaa el-Fna, the famous main square, filled with orange juice stalls, snake charmers, musicians and storytellers. In the evening, it becomes a huge open-air food market. Your clients can relax at a rooftop café overlooking the square. The tour lasts around three hours.'],
  ],
  'Atlas Mountains Day Trip': [
    ['Pickup in Marrakech', 'Your clients are collected from their riad or hotel in Marrakech in the morning and drive south towards the High Atlas Mountains. Within an hour, the city gives way to olive groves, red earth villages and snow-capped peaks for much of the year. The guide explains the landscape and the Amazigh (Berber) culture of the mountain communities.'],
    ['Asni village and market', 'The first stop is often Asni, a village on the road to the mountains. On market days, usually Saturday, people from the surrounding villages come to buy and sell livestock, vegetables, spices and household goods. It is an authentic glimpse into rural life, and the guide helps your clients understand what they see.'],
    ['Imlil and the valley walk', 'The road climbs to Imlil, a village at around 1,740 metres, at the foot of Mount Toubkal, the highest peak in North Africa. With the guide, your clients walk through walnut groves, terraced fields and small villages. The walks are chosen to suit the group’s fitness, from gentle strolls to longer hikes. Good walking shoes are recommended.'],
    ['Lunch with a Berber family', 'Lunch is served in the home of a local family, usually with mint tea, bread, salads and a tagine. Your clients sit on cushions and experience traditional Amazigh hospitality. Many homes have rooftop terraces with views of the mountains. It is often the most memorable part of the day for many visitors.'],
    ['Return to Marrakech', 'In the afternoon, the group drives back to Marrakech, often stopping at viewpoints or an argan oil cooperative run by local women, where your clients can see how the oil is produced. They arrive back in the city in the late afternoon, around eight hours after pickup. Tips for the guide and family are appreciated.'],
  ],
  'Agafay Desert Dinner': [
    ['Afternoon pickup', 'Your clients are collected from their riad or hotel in Marrakech in the afternoon for the drive to the Agafay desert, about 40 minutes to an hour south-west of the city. Unlike the sand dunes of the Sahara, Agafay is a stony desert of rolling hills, with views of the Atlas Mountains behind. It is the easiest way to experience a desert evening from Marrakech.'],
    ['Camel ride', 'On arrival at the camp, your clients take a short camel ride across the desert hills, led by a local handler. The ride usually lasts around 20 to 30 minutes and gives a real sense of the space and silence of the desert. Quad bike or buggy rides can often be added at an extra cost.'],
    ['Sunset over the Atlas', 'As the sun sets, the desert and mountains glow in shades of gold, orange and pink. Your clients can enjoy the view from the camp with mint tea, or walk to a nearby viewpoint. It is one of the most beautiful sunsets in Morocco and a perfect moment for photos.'],
    ['Moroccan dinner', 'Dinner is served in a large tent or outdoors under lanterns, with traditional Moroccan dishes such as salads, tagines, couscous and fruit, depending on the camp. Drinks are usually paid for separately. The atmosphere is relaxed and romantic, making it a favourite for couples and small groups.'],
    ['Live music and stargazing', 'After dinner, musicians play traditional Gnawa or Berber music around the fire. With little light pollution, the night sky is full of stars. Your clients return to Marrakech at around 10pm or 11pm, about five hours after pickup. Warm layers are recommended because desert nights can be cool, especially in winter.'],
  ],
  'Jardin Majorelle Visit': [
    ['Arrival in Gueliz', 'Your clients arrive at the Jardin Majorelle in the Gueliz district, the modern part of Marrakech, at their reserved entry time. Timed tickets are required and help manage the crowds. The garden is best visited early in the morning or late in the afternoon, when the light is softer and it is less busy.'],
    ['The gardens', 'The garden was created by French painter Jacques Majorelle from 1923 and later bought and restored by Yves Saint Laurent and Pierre Bergé. Your clients walk along paths shaded by bamboo, palms and cacti from around the world, past fountains, lily ponds and pots painted in bright yellow and green.'],
    ['The blue villa', 'At the heart of the garden stands the cubist studio of Jacques Majorelle, painted in a striking cobalt blue that is now known as Majorelle Blue. It is one of the most photographed buildings in Morocco. The contrast between the blue walls, yellow details and green plants makes it a favourite spot for photographs.'],
    ['Pierre Bergé Museum of Berber Arts', 'Inside the former studio, the Pierre Bergé Museum of Berber Arts displays jewellery, textiles, weapons, carpets and everyday objects from the Amazigh (Berber) peoples of North Africa. The dark, star-lit room of jewellery is particularly beautiful. The museum requires a separate ticket, which our team can add.'],
    ['Yves Saint Laurent Museum', 'Next door, the Musée Yves Saint Laurent Marrakech presents the designer’s work and his relationship with Morocco, with rotating exhibitions of haute couture, sketches and photographs. Entry is not included but can be combined. After the visit, your clients can explore the cafés and boutiques of Gueliz. The garden visit takes around two hours.'],
  ],

  // Paris
  'Eiffel Tower Summit': [
    ['Arrival and security', 'Your clients arrive at the Eiffel Tower on the Champ de Mars at least 30 minutes before their reserved time. After passing security at the entrance to the site, they head to the pillar shown on their ticket. With a reserved entry time, they avoid the long ticket queues, although there may still be a short wait for the lift at busy times.'],
    ['Lift to the second floor', 'The first lift carries your clients up the leg of the tower to the second floor, 115 metres above the ground. The ride itself is an experience, as the lift climbs at an angle through the iron structure. From the windows, they can see the metalwork up close and the city opening up below.'],
    ['Second floor views', 'The second floor offers some of the best views of Paris, as the landmarks are still close enough to recognise easily. Your clients can see the Seine, the Trocadéro, the Arc de Triomphe, the Louvre, Notre-Dame and Montmartre. There are shops and a buffet on this level, as well as the Jules Verne restaurant, which needs a separate reservation.'],
    ['Lift to the summit', 'From the second floor, a separate lift takes your clients to the summit, 276 metres above the ground. The top level has an enclosed viewing platform and an open-air deck protected by safety netting. On a clear day, the view extends up to 60 kilometres. Gustave Eiffel’s restored office, with wax figures, can be seen at the top.'],
    ['Champagne bar and descent', 'At the summit, your clients can raise a glass at the champagne bar, at an extra cost. They then take the lift back down to the second floor, where they can walk down the stairs to the first floor, with its glass floor, before returning to the ground. The whole visit takes around two hours.'],
  ],
  'Louvre Guided Tour': [
    ['Meeting at the Louvre', 'Your clients meet their guide near the Louvre, usually close to the Pyramid or the Carrousel du Louvre entrance. With reserved entry, they avoid the longest queues and go through security. Headsets are handed out so everyone can hear the guide in the busy galleries. The guide explains the history of the palace, which was a royal residence before becoming a museum.'],
    ['Medieval Louvre and Egyptian antiquities', 'Many tours begin in the foundations of the medieval fortress, where the walls of the original castle built around 1190 can still be seen. The guide may also lead the group through the Egyptian antiquities, one of the world’s finest collections, including the Great Sphinx of Tanis and objects from daily life in ancient Egypt.'],
    ['Venus de Milo', 'The tour continues to the Greek sculpture galleries to see the Venus de Milo, carved around 100 BC and discovered on the island of Milos in 1820. The guide explains why it became so famous and the mystery of its missing arms. Nearby, other classical sculptures show how the Greeks represented the human body.'],
    ['Winged Victory of Samothrace', 'At the top of the Daru staircase stands the Winged Victory of Samothrace, a Hellenistic sculpture of the goddess Nike landing on the prow of a ship. Its sense of movement is breathtaking, and its position at the top of the stairs makes it one of the most dramatic sights in the museum.'],
    ['Mona Lisa and Italian painting', 'The tour ends in the Italian painting galleries with the Mona Lisa, painted by Leonardo da Vinci in the early 16th century. The room is busy, but the guide helps your clients get a good view and explains why the painting is so famous. Nearby, the Wedding at Cana by Veronese is the largest painting in the museum. Your clients can stay on after the tour.'],
  ],
  'Seine Dinner Cruise': [
    ['Boarding near the Eiffel Tower', 'Your clients arrive at the pier near the Eiffel Tower in the evening, around 30 minutes before departure. After checking in, they are shown to their table on a glass-roofed boat, which offers views on all sides. Dress is usually smart casual. Some cruises offer two sittings, with the later one offering the best night views.'],
    ['Welcome and starter', 'As the boat leaves the pier, guests are served an aperitif and the first course of a three-course French meal. Live music often plays in the background. The boat heads upstream along the Seine, and the Eiffel Tower is seen from the water in all its glory. Wine and drinks depend on the chosen menu.'],
    ['Musée d’Orsay and the Louvre', 'The cruise passes the Musée d’Orsay, a former railway station that now houses a great collection of Impressionist art, and the long façade of the Louvre on the opposite bank. The boat glides under historic bridges, including the Pont Alexandre III, decorated with gold statues and lamps, and the Pont Neuf, the oldest bridge in Paris.'],
    ['Île de la Cité and Notre-Dame', 'The main course is served as the boat reaches the Île de la Cité and the Île Saint-Louis, the historic heart of Paris. Your clients see Notre-Dame Cathedral from the river, reopened after its restoration following the 2019 fire, as well as the Conciergerie, where Marie Antoinette was imprisoned.'],
    ['The sparkling Eiffel Tower', 'On the way back, dessert is served as the boat returns towards the Eiffel Tower. After dark, the tower sparkles with thousands of lights for five minutes at the start of every hour, a truly magical sight from the river. The cruise lasts around two and a half hours, and our team can add a transfer back to the hotel.'],
  ],
  'Palace of Versailles Day Trip': [
    ['Departure from Paris', 'Your clients meet their guide at a central Paris meeting point in the morning and travel to Versailles by coach, about 40 minutes to an hour away. The guide explains the history of the palace on the way, from Louis XIII’s hunting lodge to the grand palace built by Louis XIV, the Sun King, and the downfall of the monarchy during the French Revolution.'],
    ['Skip-the-line entry and the Royal Chapel', 'With skip-the-line entry, your clients avoid the long queues that are common at Versailles, although there is still a security check. Inside, the guide shows them the Royal Chapel, where the royal family attended Mass daily, with its marble floor, painted ceilings and gilded organ. It is one of the most beautiful chapels in France.'],
    ['King’s State Apartments', 'The tour continues through the King’s State Apartments, a series of rooms dedicated to the planets and the gods of Olympus, decorated with marble, gold, paintings and chandeliers. Each room had a specific purpose in court life. The guide explains the strict etiquette of the court and the daily ceremonies of the king.'],
    ['Hall of Mirrors', 'The highlight of the palace is the Hall of Mirrors, 73 metres long, with 357 mirrors facing 17 windows overlooking the gardens. It was used for ceremonies and celebrations, and in 1919 the Treaty of Versailles was signed here, ending the First World War. Your clients then visit the Queen’s State Apartments, where Marie Antoinette lived.'],
    ['Gardens of Versailles', 'After the palace, your clients explore the vast formal gardens designed by André Le Nôtre, with fountains, statues, flower beds and the Grand Canal. On selected days, the Musical Fountains show brings the fountains to life with Baroque music. They can also visit the Trianon palaces and Marie Antoinette’s Estate before returning to Paris.'],
  ],
}
